### ISSUE TITLE
Exchange scepter had a crash : ConcurrentModificationException

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#114]
the gentle (blue) one, using 3x3 with overlapping areas, the first time it seemd to not work and the second time crashed.

Seems to be a knock on of https://github.com/PrinceOfAmber/Cyclic/issues/99

Also, they could use tooltips while im in there. another enhancement would be to change how they break blocks so they dont notify neighbours, EX: using this with doors or toches on top will break those things.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  LoadingPlugin (Quark-r1.0-56.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.2.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 01/10/16 6:23 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:280)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 464801296 bytes (443 MB) / 1134034944 bytes (1081 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2094 Optifine OptiFine_1.10.2_HD_U_C3 75 mods loaded, 75 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAA   Forge{12.18.1.2094} [Minecraft Forge](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAA   backpacks16840{3.1.2} [Backpacks!](zz-backpacks 1.10.2 - 3.1.2.jar) 
    UCHIJAAAA   JEI{3.9.5.255} [Just Enough Items](jei_1.10.2-3.9.5.255.jar) 
    UCHIJAAAA   AppleCore{2.0.1} [AppleCore](AppleCore-mc1.10.2-2.0.1.jar) 
    UCHIJAAAA   appleskin{1.0.4} [AppleSkin](AppleSkin-mc1.10.2-1.0.4.jar) 
    UCHIJAAAA   arrowcammod{2.2.0} [Arrow Cam Mod](ArrowCamMod-1.10.2-2.2.0.jar) 
    UCHIJAAAA   Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-1.10.2-0.3.0.30.jar) 
    UCHIJAAAA   betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UCHIJAAAA   BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
    UCHIJAAAA   infinitylib{1.10.2-@MAJOR@.@MINOR@.@REVIS@} [InfinityLib](infinityLib-0.1.jar) 
    UCHIJAAAA   boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull](boatifull-0.1.jar) 
    UCHIJAAAA   BuildersGuides{1.10.2-1.0.2} [Builder's Guides](buildersguides-1.10.2-1.0.2.jar) 
    UCHIJAAAA   ChunkAnimator{1.2} [Chunk Animator](ChunkAnimator-MC1.9.4-1.2.jar) 
    UCHIJAAAA   clienttweaks{1.1.13} [Client Tweaks](ClientTweaks_1.10.2-1.1.13.jar) 
    UCHIJAAAA   commandkeybindings{6.0.2.10} [Command Keybindings](CommandKeybindings-Forge-6.0.2.10.jar) 
    UCHIJAAAA   MineTweaker3{3.0.11} [MineTweaker 3](CraftTweaker-1.10.2-3.0.11.jar) 
    UCHIJAAAA   cs{1.0.3} [Configurable Villager to Door Ratio](cs-1.0.3.jar) 
    UCHIJAAAA   CustomBackgrounds{1.0} [Custom Backgrounds](CustomBackgrounds-MC1.9.4-1.1.jar) 
    UCHIJAAAA   cyclicmagic{1.7.10} [Cyclic](Cyclic-1.10.2-1.7.10.jar) 
    UCHIJAAAA   Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UCHIJAAAA   disenchanter{1.4} [Disenchanter](disenchanter-[1.9.4]1.4.jar) 
    UCHIJAAAA   dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial](DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
    UCHIJAAAA   endercompass{1.2.3.2} [Ender Compass](EnderCompass-1.9.x-1.2.3.2.jar) 
    UCHIJAAAA   EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UCHIJAAAA   extraalchemy{0.3.0.1-beta} [Extra Alchemy](extraalchemy-0.3.0.1-beta.jar) 
    UCHIJAAAA   shadowmc{3.4.7} [ShadowMC](ShadowMC-1.10.2-3.4.7.jar) 
    UCHIJAAAA   ExtraRails{1.1.1} [Extra Rails](ExtraRails-1.10.2-1.1.1.jar) 
    UCHIJAAAA   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.10.2-1.2.2.jar) 
    UCHIJAAAA   frt{6.4.4} [Fire's Random Things](FiresRandomThings-6.4.4.jar) 
    UCHIJAAAA   fe{1.2.1} [Food Expansion](FoodExpansion1.2.4-1.10.2.jar) 
    UCHIJAAAA   forgecreeperheal{1.3.0} [Forge Creeper Heal](forgecreeperheal-1.10.2-1.3.0.jar) 
    UCHIJAAAA   exp{1.1} [Exp Seedling Mod](GiacomosExperienceSeedling1.9.4-1.1.jar) 
    UCHIJAAAA   giacomostravelogue{1.01} [Giacomoâ€™s Travelogue](GiacomosTravelogue1.10.2-1.01.jar) 
    UCHIJAAAA   GlobalGameRules{1.0} [Global GameRules](GlobalGameRules-1.10.2-1.0.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks](Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   gravelminer{4.1.8} [GravelMiner](GravelMiner_1.10.2-4.1.8.jar) 
    UCHIJAAAA   HungerInPeace{1.0.0} [Hunger In Peace](HungerInPeace-mc1.9.4-1.0.0.jar) 
    UCHIJAAAA   imc{1.12.1} [Improving Minecraft](Improving Minecraft-1.12.1.jar) 
    UCHIJAAAA   inventorysorter{0.10.0+42} [Simple Inventory sorting](inventorysorter-1.10-0.10.0+42.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   kleeslabs{3.3.5} [KleeSlabs](KleeSlabs_1.10.2-3.3.5.jar) 
    UCHIJAAAA   login_shield{1.10.2-11-gb29eaad} [Login Shield](Login_Shield-1.10.2-11-gb29eaad.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCHIJAAAA   minecraftcalculator778{3.1.4} [MineCalc](MineCalc-1.10.2-3.1.4.jar) 
    UCHIJAAAA   mineTunes{1.2-9} [mineTunes](MineTunes 1.2-9.jar) 
    UCHIJAAAA   mobends{0.22.5} [Mo'Bends](mobends-0.22.5_for_MC-1.10.2.jar) 
    UCHIJAAAA   ModLister{1.10.2-2.1.8} [ModLister](ModLister-1.10.2-2.1.8.jar) 
    UCHIJAAAA   moreanvils{6.0.2.11} [More Anvils](MoreAnvils-Forge-6.0.2.11.jar) 
    UCHIJAAAA   Morpheus{1.10.2-3.1.7} [Morpheus](Morpheus-1.10.2-3.1.7.jar) 
    UCHIJAAAA   mousetweaks{2.6.4} [Mouse Tweaks](MouseTweaks-2.6.4-mc1.10.2.jar) 
    UCHIJAAAA   netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAAAA   samsocean{1.0.0} [Classic Oceans](OceanFloor-1.10.2-1.0.1.jar) 
    UCHIJAAAA   PersistentBits{1.0.5} [Persistent Bits](PersistentBits-1.10.2-1.0.5.jar) 
    UCHIJAAAA   progressiveautomation{1.6.51} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJAAAA   rblr{6.0.2.10} [Rabbits Breed Like Rabbits](RabbitsBreedLikeRabbits-Forge-6.0.2.10.jar) 
    UCHIJAAAA   randomore{1.3.1} [Randomite Ore](RandomiteOre-1.3.1-MC1.10.2.jar) 
    UCHIJAAAA   Schematica{1.7.8.151} [Schematica](Schematica-1.10.2-1.7.8.151-universal.jar) 
    UCHIJAAAA   SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors](SimilsaxTranstructors-1.10.2.18.jar) 
    UCHIJAAAA   soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.9.4.jar) 
    UCHIJAAAA   SparksHammers{1.10.2-1.3.1} [Spark's Hammers](SparksHammers-1.10.2-1.3.1.jar) 
    UCHIJAAAA   Stackie{1.6.0.44} [Stackie](Stackie-1.10.2-1.6.0.44-universal.jar) 
    UCHIJAAAA   storagenetwork{1.12.9} [Storage Network](StorageNetwork-1.9.4-1.12.9.jar) 
    UCHIJAAAA   supercraftingframe{1.2.1.87} [Super Crafting Frame](supercraftingframe-1.10.2-1.2.1.87.jar) 
    UCHIJAAAA   lteleporters{1.1.3} [Lemon's Simple Teleporters](teleporters-1.1.3.jar) 
    UCHIJAAAA   theoneprobe{1.1.2} [The One Probe](theoneprobe-1.10-1.1.2.jar) 
    UCHIJAAAA   thutcore{3.5.0} [ThutCore](thutcore-1.9.4-3.5.0.jar) 
    UCHIJAAAA   thuttech{4.0.5} [Thut's Tech](thuttech-4.0.5.jar) 
    UCHIJAAAA   tp{1.0.0} [Tiny Progressions](tinyprogressions-1.10.2-1.0.6-release.jar) 
    UCHIJAAAA   tombmanygraves{1.10.2-2.1.10} [Tomb Many Graves](TombManyGraves-1.10.2-2.1.10.jar) 
    UCHIJAAAA   underphangables{1.0.2} [Underp Hangables](underphangables-1.10.2-1.0.2.jar) 
    UCHIJAAAA   va{1.10.2-1.5} [Vanilla Automation](va-1.10.2-1.5.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.2.jar)
  brad16840.common.asm.ClassTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['Lothrazar'/387, l='Kingdoms', x=-272.52, y=76.25, z=255.86]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.10.2_HD_U_C3
    Render Distance Chunks: 6
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 369.09
    OpenGlRenderer: GeForce GT 730/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

**Comment by PrinceOfAmber** [comment]
possibly related http://stackoverflow.com/questions/18752320/trycatch-concurrentmodificationexception-catching-30-of-the-time

**Comment by PrinceOfAmber** [comment]
Fixed in release Cyclic-1.10.2-1.7.12.jar

**Comment by PrinceOfAmber** [comment]
This exception happened again, not sure if it was this item or if it was the Empty Sack of Holding

**Comment by PrinceOfAmber** [comment]
pastebin from hypermine ssp http://pastebin.com/CYRJBTxK

**Comment by PrinceOfAmber** [comment]
This should be fixed in build 1.7.22 https://minecraft.curseforge.com/projects/cyclic/files/2340924
