### ISSUE TITLE
Crash with EntityShearingBolt

### ISSUE THREAD

**Issue by LemADEC** [PrinceOfAmber/Cyclic#120]
Server crashes when player try to use Ender Shears.
```
java.lang.NullPointerException: Ticking entity
        at com.lothrazar.cyclicmagic.entity.projectile.EntityShearingBolt.func_70184_a(EntityShearingBolt.java:50)
        at net.minecraft.entity.projectile.EntityThrowable.redirect$onProjectileImpact$zfl000(EntityThrowable.java:99)
        at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:250)
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:143)
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zji000(WorldServer.java:1302)
        at net.minecraft.world.World.func_72866_a(World.java:1964)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:1934)
        at net.minecraft.world.World.func_72939_s(World.java:1210)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:709)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at com.lothrazar.cyclicmagic.entity.projectile.EntityShearingBolt.func_70184_a(EntityShearingBolt.java:50)
        at net.minecraft.entity.projectile.EntityThrowable.redirect$onProjectileImpact$zfl000(EntityThrowable.java:99)
        at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:250)
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:143)
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zji000(WorldServer.java:1302)
        at net.minecraft.world.World.func_72866_a(World.java:1964)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
        Entity Type: cyclicmagic.cyclicmagic.woolbolt (com.lothrazar.cyclicmagic.entity.projectile.EntityShearingBolt)
        Entity ID: 21555
        Entity Name: entity.cyclicmagic.cyclicmagic.woolbolt.name
        Entity's Exact location: -2322.16, 74.66, 2802.98
        Entity's Block location: World: (-2323,74,2802), Chunk: (at 13,4,2 in -146,175; contains blocks -2336,0,2800 to -2321,255,2815), Region: (-5,5; contains chunks -1$
        Entity's Momentum: 0.45, -0.26, 1.35
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1210)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:709)

```
Using Cyclic-1.10.2-1.7.10.jar

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this ill get a fix out soon

**Comment by PrinceOfAmber** [comment]
Do you know what version of the mod you were using? and was it a sheep you hit or a modded entity?

**Comment by PrinceOfAmber** [comment]
Was there more to the crash log? Sometimes it lists out every single mod that was installed at the top or bottom.  My first guess is that maybe there is a mod that somehow affects sheep.getFleeceColor(); so i want to look into that more

**Comment by PrinceOfAmber** [comment]
Im adding a ton saftey checks and error handling in 1.7.14 , so at least if this doesnt happen again, it will do the same thing as if it hit a cow (drop as item) and hopefully not crash.   However, i wasnt able to reproduce the issue on vanilla sheep, so im not 100% sure of the fix.

**Comment by PrinceOfAmber** [comment]
Hopefully have this fixed in the new release, or if its not fixed my handlers should stop the crash..  In both single and multiplayer, all vanilla sheep are working fine for me. If it happens again please report it    https://minecraft.curseforge.com/projects/cyclic/files/2336276

**Comment by LemADEC** [comment]
Issue is reproduced in single player according to one of the player, so I didn't list Sponge version and plugins from the crash.

**Comment by LemADEC** [comment]
Issue is reproduced in SSP with Sponge when targeting a sheep. After the crash, ender shear item is on the ground, sheep is sheared but no wool item were dropped.
Targeting a sheared sheep or a block doesn't reproduce the issue.

The updated mod effectively fix the issue but says null on console:
[22:32:20] [Server thread/ERROR] [cyclicmagic/]: null
