### ISSUE TITLE
Charms causing Internal Error

### ISSUE THREAD

**Issue by PieMaster61** [PrinceOfAmber/Cyclic#1318]
Minecraft Version: 1.15.2

Forge Version: 31.1.12

Mod Version: 0.1.10

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Created a fire charm. The instant I touched lava and caught fire I was kicked repeatedly by an Internal Server Error
I was also told the other charms caused problems as well.

Log file link:
[2020-02-19-4.log.gz](https://github.com/Lothrazar/Cyclic/files/4228383/2020-02-19-4.log.gz)

Video/images/gifs (direct upload or link): Did not think of taking a screenshot

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by kreezxil** [comment]
I have a player with this issue right now in my foreshadowing mod pack, but it seems to have affected the entire server.

this is being spammed in the console:
```
[08:21:55] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /65.129.223.32:61506
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:424) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
Caused by: java.lang.NoSuchMethodError: com.lothrazar.cyclic.util.UtilParticle.spawnParticle(Lnet/minecraft/world/World;Lnet/minecraft/particles/IParticleData;Lnet/minecraft/util/math/BlockPos;I)V
        at com.lothrazar.cyclic.item.bauble.CharmBase.tryFireTick(CharmBase.java:59) ~[?:1.15.2-0.1.10] {re:classloading}
        at com.lothrazar.cyclic.item.bauble.CharmBase.func_77663_a(CharmBase.java:49) ~[?:1.15.2-0.1.10] {re:classloading}
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2103) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:classloading,pl:accesstransformer:B}
        ... 8 more
```

Forge: 31.1.14
MC: 1.15.2
Cyclic: 1.15.2-0.1.10

**Comment by purestone9** [comment]
I am the player in question that Kree is talking about here. For me the situation is almost exactly the same execpt im using the Charm Amulet

**Comment by purestone9** [comment]
The issue dose not happen in single player, just in multiplayer

**Comment by Yoosk** [comment]
I guess the same thing is keep happening on our server as well.
[The relevant part of log](https://s.yoosk.pl/jafJk)

**Comment by minecrafterseppe** [comment]
can confirm still happens in 1.15.2 on servers

**Comment by Heliopause0916** [comment]
The same problem. 
Fortunately only fire charms causes "internal server error".
And others(void, poison, wither) works perfectly right.
Forge version 31.1.19，Mod version 0.1.11

**Comment by failsafe42** [comment]
Same thing is happening to me on minecraft version 1.15.2 mod version 1.19.14

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
