### ISSUE TITLE
Charm Talisman Crash

### ISSUE THREAD

**Issue by lynaevm** [PrinceOfAmber/Cyclic#1381]
Minecraft Version: 1.15

Forge Version: Whatever Omnia 1.1.0 is, can't find it lol

Mod Version:  0.3.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

When wearing the Charm Talisman in bauble slot, I started crashing any time I was set on fire.  Crash report included:

Caused by: java.lang.NoSuchMethodError: com.lothrazar.cyclic.util.UtilParticle.spawnParticle(Lnet/minecraft/world/World;Lnet/minecraft/particles/IParticleData;Lnet/minecraft/util/math/BlockPos;I)V
        at com.lothrazar.cyclic.item.bauble.CharmBase.tryFireTick(CharmBase.java:59) ~[?:1.15.2-0.3.0] {re:classloading}
        at com.lothrazar.cyclic.item.bauble.CharmBase.func_77663_a(CharmBase.java:49) ~[?:1.15.2-0.3.0] {re:classloading}

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Fixed in previous version, modpack needs to get latest https://github.com/Lothrazar/Cyclic/issues/1358
