### ISSUE TITLE
Robot Entity Crash

### ISSUE THREAD

**Issue by Joofes** [PrinceOfAmber/Cyclic#1545]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
While I'm loading the game Cyclic keeps giving crashing my game and saying that there is a kill.entity.robot error. I thought this was a problem with fast workbenches but I installed fast workbenches and it still crashes.

Log file link:
[crash-2020-10-21_09.58.38-client.txt](https://github.com/Lothrazar/Cyclic/files/5416417/crash-2020-10-21_09.58.38-client.txt)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

Sorry if I didn't give enough info here is the modpack which causes cyclic to crash the game, take cyclic out and everything else works fine https://drive.google.com/drive/folders/1W5XrM5mH4oJCOpVI_G08FkdEm0I_G7QR?usp=sharing

**Comment by Joofes** [comment]
Sorry if I didn't give enough info here is the modpack which causes cyclic to crash the game, take cyclic out and everything else works fine https://drive.google.com/drive/folders/1W5XrM5mH4oJCOpVI_G08FkdEm0I_G7QR?usp=sharing

**Comment by Lothrazar** [comment]
i did a search of the log file trying to find any errors coming from cyclic. only time 'cyclic' showed up was in the mod list
 `| LCH   | cyclicmagic    `

So it loaded.

Crash says this,. but starting this up in 1.20.7+ i dont see this happening, single player or server? does it still happen if you remove only cyclic mod and nothing else

`
Description: Initializing game

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.robot.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.robot.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.robot
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
	at mod.mcreator.mmadd.registerEntities(mmadd.java:167)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1009_mmadd_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`

**Comment by Lothrazar** [comment]
in the lang file for the entity spawned by item.robot_spawner.name, my entity name is entity.robot.name=Target Dummy . but it doesnt register any stats.

**Comment by Lothrazar** [comment]
This is where entity gets registered. It uses the scope of Const.MODID which is the 'cyclicmagic' mod id.  

I guess maybe is there a conflict with some other mod that makes a "cyclicmagic:robot"? not sure 
https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/item/crashtestdummy/ItemCrashSpawner.java#L37

**Comment by Joofes** [comment]
To answer your question specifically removing Cyclic causes the game to work fine. I do really love your mod and am trying to see if I can find what mod conflicts with it. Is there a version with no robot at all? Are their cyclic compatibility mods? My mod pack is supposed to be more like a factory so that's where cyclic comes it with many useful objects like auto crafters, and block placers/breakers.

**Comment by Joofes** [comment]
I also wanted to tell you that is the exact same crash message I got when I try with any version. And I use my mod pack for server and single player but I can't even open the game so that's the first issue. I basically hope you can provide a version with no robot, or if you can recommend other mod packs that can add auto block placers/breakers or an autocrafter.
