### ISSUE TITLE
Server Timed Out : com.lothrazar.cyclicmagic.playerupgrade.PacketOpenGuiOnServer.onMessage

### ISSUE THREAD

**Issue by xzefir** [PrinceOfAmber/Cyclic#1554]
Minecraft Version: 
1.12.2

Forge Version: 
1.12.2-14.23.5.2854

Mod Version: 
1.12.2-1.20.8

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
My server timed out for no apparent reason, I have to kill the server because it is not responding. Before timed out a lot of error is present in the logs mentioning your mod

Log file link:
Part of the server log
https://www.dropbox.com/s/ag7bq37rcna664x/logs.log?dl=0

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
```
[18:07:29] [Netty Epoll Server IO #9/ERROR] [FML]: There was a critical exception handling a packet on channel cyclicmagic
java.lang.RuntimeException: PLAYER target expects a Player arg
```

Probably this? And:

```
[18:07:28] [Netty Epoll Server IO #0/ERROR] [FML]: There was a critical exception handling a packet on channel cyclicmagic
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Netty Epoll Server IO #0, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.event.SpongeCauseStackManager.pushCauseFrame(SpongeCauseStackManager.java:240) ~[SpongeCauseStackManager.class:1.12.2-2838-7.3.0]
	at net.minecraft.entity.player.EntityPlayer.dropItem(EntityPlayer.java:4768) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.dropItem(EntityPlayer.java:4732) ~[aed.class:?]
	at net.minecraft.inventory.Container.onContainerClosed(Container.java:489) ~[afr.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.closeContainer(EntityPlayerMP.java:1022) ~[oq.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:92) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at com.lothrazar.cyclicmagic.playerupgrade.PacketOpenGuiOnServer.onMessage(PacketOpenGuiOnServer.java:59) ~[PacketOpenGuiOnServer.class:?]
	at com.lothrazar.cyclicmagic.playerupgrade.PacketOpenGuiOnServer.onMessage(PacketOpenGuiOnServer.java:34) ~[PacketOpenGuiOnServer.class:?]
```
