### ISSUE TITLE
Terra Preta Causing Server Crashes and Corrupt World

### ISSUE THREAD

**Issue by ethmeyer** [PrinceOfAmber/Cyclic#1654]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 0.10.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): I was placing Terra Preta blocks in square big enough for a harvester and item collected combo and then the server crashed and the world got corrupted.

Log file link: java.lang.ClassCastException: net.minecraft.block.LilyPadBlock cannot be cast to net.minecraft.block.IGrowable
are you generating any new terrain?
like loading new chunks?
-- Head --
Thread: Server thread
Stacktrace:
    at com.lothrazar.cyclic.block.soil.TileTerraPreta.doGrowth(TileTerraPreta.java:85) ~[cyclic:1.16.4-0.10.1] {re:classloading}
    at com.lothrazar.cyclic.block.soil.TileTerraPreta.func_73660_a(TileTerraPreta.java:69) ~[cyclic:1.16.4-0.10.1] {re:classloading}
-- Block entity being ticked --
Details:
    Name: cyclic:terra_preta // com.lothrazar.cyclic.block.soil.TileTerraPreta
    Block: Block{cyclic:terra_preta}
    Block location: World: (347,51,-965), Chunk: (at 11,3,11 in 21,-61; contains blocks 336,0,-976 to 351,255,-961), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
    Block: Block{cyclic:terra_preta}
    Block location: World: (347,51,-965), Chunk: (at 11,3,11 in 21,-61; contains blocks 336,0,-976 to 351,255,-961), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Stacktrace:
    at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

Video/images/gifs (direct upload or link):

**Comment by trunksbomb** [comment]
This is fixed in the current release (1.0.1)

**Comment by Lothrazar** [comment]
yep was fixed december 21 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3145349
