### ISSUE TITLE
Using Saturation Potion on Pharos Beacon set to one setting crashes world

### ISSUE THREAD

**Issue by RedX04** [PrinceOfAmber/Cyclic#1690]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Mod Version: 1.20.4

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened): I was setting up a saturation beacon on a multiplayer server and was looking through the entity type filter while it was active and it crashed the server. I tested it on a single player and it still had the issue.

Log file link:
[2021-01-12-6.log.gz](https://github.com/Lothrazar/Cyclic/files/5805023/2021-01-12-6.log.gz)

Video/images/gifs (direct upload or link): 
https://drive.google.com/file/d/15fqjW2rr5BQJ7Lji2wwxm9bigwL_S-zM/view?usp=sharing

**Comment by Lothrazar** [comment]
tServer.class:?]
	... 4 more
[13:57:33] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\_gdl\instances\Stable\crash-reports\crash-2021-01-12_13.57.32-server.txt
[13:57:33] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[13:57:33] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[13:57:33] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/12/21 1:57 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.passive.EntitySquid cannot be cast to net.minecraft.entity.player.EntityPlayer
	at com.lothrazar.cyclicmagic.potion.effect.PotionSaturation.tick(PotionSaturation.java:51)
	at com.lothrazar.cyclicmagic.potion.EventPotionTick.onEntityUpdate(EventPotionTick.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_957_EventPotionTick_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lothrazar** [comment]
was resolved by https://github.com/Lothrazar/Cyclic/issues/1470 in 1.20.5+
