### ISSUE TITLE
Ender Library Repeated Crash with AE

### ISSUE THREAD

**Issue by seanwineman** [PrinceOfAmber/Cyclic#1827]
Minecraft Version: 1.6.5

Forge Version: 36.1.2

Mod Version: 1.2.7

Single Player or Server: locally hosted server

Describe problem (what you were doing; what happened; what should have happened):
I used an export bus to fill the ender controller with books, the server started slowing down considerably before crashing and now is crashing on load. I'm assuming the crash on load is because the chunk is loaded

Log file link:

https://github.com/seanwineman/Cyclic-Crash/blob/7b454c4907e639a63ec77a4f997b636a2c6c0832/ATM6

**Comment by Lothrazar** [comment]
`


      
      
        

      
      
        java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
      
      
        	at java.util.Arrays.copyOf(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at java.lang.AbstractStringBuilder.append(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at net.minecraft.nbt.ListNBT.toString(SourceFile:112) ~[?:?] {re:mixin,re:classloading}
      
      
        	at java.lang.String.valueOf(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_271] {}
      
      
        	at com.lothrazar.cyclic.util.UtilEnchant.doBookEnchantmentsMatch(UtilEnchant.java:48) ~[cyclic:1.16.5-1.2.7] {re:classloading}
      
      
        	at 
com.lothrazar.cyclic.block.endershelf.EnderControllerItemHandler.insertItemElsewhere(EnderControllerItemHandler.java:59)
 ~[cyclic:1.16.5-1.2.7] {re:classloading}

`
