### ISSUE TITLE
Server ATM6 1.16.5    Version 1.7.1

### ISSUE THREAD

**Issue by SpartaWarsec** [PrinceOfAmber/Cyclic#1883]
Minecraft Version: 

Forge Version: 
forge-1.16.5-36.1.32

Mod Version: 

Single Player or Server:

SERVER spam in consol

Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

09:05:13
UUID of player XXXXXXX is 
Server thread/ERROR09:05:20
Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
Server thread/INFO09:05:21
Mean tick: 36ms increasing chunk view distance to: 8
09:05:34
Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@130eca60
Server thread/ERROR09:05:34
? overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
C PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
Server thread/INFO09:05:34
XXXXXXX[/192.168.2.122:60391]: logged in with entity id 59317 at (-1541.7228535736745, 35.0, -451.62623550674346)
XXXXXXX joined the game
Server thread/ERROR09:05:34
? overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
C PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

Log file link:

Video/images/gifs (direct upload or link):

**Comment by SpartaWarsec** [comment]
Timer-0/INFO09:46:39
[java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NumberFormatException: For input string: "f30fd856673f_cyclic"
[java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.NumberFormatException.forInputString(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Long.parseLong(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Long.valueOf(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Long.decode(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.UUID.fromString(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at com.darkere.crashutils.DataStructures.PlayerActivityHistory.lambda$new$0(PlayerActivityHistory.java:45)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.Iterator.forEachRemaining(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at com.darkere.crashutils.DataStructures.PlayerActivityHistory.<init>(PlayerActivityHistory.java:30)
[java.lang.ThreadGroup:uncaughtException:-1]: at com.darkere.crashutils.CrashUtils$1.run(CrashUtils.java:157)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.TimerThread.mainLoop(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:-1]: at java.util.TimerThread.run(Unknown Source)
