### ISSUE TITLE
shap builder

### ISSUE THREAD

**Issue by undead45** [PrinceOfAmber/Cyclic#1909]
Minecraft Version: 
1.16.5
Forge Version: 
36.22
Mod Version: 
1.3.5
Single Player or Server:
server
Describe problem (what you were doing; what happened; what should have happened):
i place down the shap builder  and up the shap bata card in it  and it craft the server and now no one can go to my base or they will be on a crash loop we are play on all the mods 6 of that helps

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Oh yeah, i can see a similar issue now that i test it the way you described , working on a fix 

```
Caused by: java.lang.NullPointerException
	at com.lothrazar.cyclic.block.shapebuilder.TileStructure.getShape(TileStructure.java:272) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lothrazar.cyclic.block.shapebuilder.TileStructure.tick(TileStructure.java:188) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}```
