### ISSUE TITLE
something in my latest log about: Unknown enchantment 'cyclic:auto_smelt'

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#1916]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.4

**Mod Version:** 1.3.8

**Single Player or Server:** single. but probably both.

**Describe problem (what you were doing; what happened; what should have happened):**
theres no problem yet. but it looks like it could be a problem. I just saw this in my latest log.

**Log file link:**
**Excerpt:**
`[02:24:49] [Render thread/ERROR]: Couldn't parse loot modifier cyclic:auto_smelt
com.google.gson.JsonSyntaxException: Unknown enchantment 'cyclic:auto_smelt'
	at net.minecraft.advancements.criterion.EnchantmentPredicate.func_217954_a(SourceFile:80) ~[?:?]
	at net.minecraft.advancements.criterion.EnchantmentPredicate$$Lambda$25570/1565339151.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.advancements.criterion.EnchantmentPredicate.func_192464_a(SourceFile:80) ~[?:?]
	at net.minecraft.advancements.criterion.EnchantmentPredicate.func_192465_b(SourceFile:95) ~[?:?]
	at net.minecraft.advancements.criterion.ItemPredicate.func_192492_a(ItemPredicate.java:146) ~[?:?]
	at net.minecraft.loot.conditions.MatchTool$Serializer.func_230423_a_(SourceFile:50) ~[?:?]
	at net.minecraft.loot.conditions.MatchTool$Serializer.func_230423_a_(SourceFile:42) ~[?:?]
	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at net.minecraftforge.common.loot.LootModifierManager.deserializeModifier(LootModifierManager.java:129) ~[?:?]
	at net.minecraftforge.common.loot.LootModifierManager.lambda$apply$0(LootModifierManager.java:115) [?:?]
	at net.minecraftforge.common.loot.LootModifierManager$$Lambda$25686/1319156912.accept(Unknown Source) [?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_51]
	at net.minecraftforge.common.loot.LootModifierManager.apply(LootModifierManager.java:113) [?:?]
	at net.minecraftforge.common.loot.LootModifierManager.func_212853_a_(LootModifierManager.java:54) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$18878/28016840.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$19222/1435704009.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) [?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$23949/1451276052.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$23946/1743925773.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18832/189129761.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) [lwjgl-glfw-3.2.2.jar:build 10]
	at imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:100) [?:1.0.2.71]
	at imgui.glfw.ImGuiImplGlfw$$Lambda$23610/1958561557.invoke(Unknown Source) [?:1.0.2.71]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1461001018.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]`

there's no crash otherwise.

as a side note, I may have autosmelt turned off due to there being other forms of auto smelt and auto smelt relics and such and the enchantment showing up too much. so that could potentially be the issue or why this was caused.

**Comment by Lothrazar** [comment]
yeah, hmm looks like it willl happen if the enchant is off in the config like you were saying
