### ISSUE TITLE
Crash minecraft if you put water over a liquid funnel

### ISSUE THREAD

**Issue by w411** [PrinceOfAmber/Cyclic#1993]
Minecraft Version: 1.18

Forge Version: 38.0.16

Mod Version: 1.6.7

Single Player or Server: yes and yes

Describe problem (what you were doing; what happened; what should have happened):

Crash minecraft if you put water over a liquid funnel

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/3/22, 3:09 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.capability.IFluidHandler.fill(net.minecraftforge.fluids.FluidStack, net.minecraftforge.fluids.capability.IFluidHandler$FluidAction)" because "sideHandler" is null
	at com.lothrazar.cyclic.block.hopperfluid.TileFluidHopper.tryExtract(TileFluidHopper.java:106) ~[%2381!:?] {re:classloading}
	at com.lothrazar.cyclic.block.hopperfluid.TileFluidHopper.tick(TileFluidHopper.java:69) ~[%2381!:?] {re:classloading}
	at com.lothrazar.cyclic.block.hopperfluid.TileFluidHopper.serverTick(TileFluidHopper.java:54) ~[%2381!:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:673) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:768) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading}
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:476) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:324) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:868) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:328) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:808) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:668) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258) ~[forge-1.18.1-39.0.10_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
	```
