### ISSUE TITLE
Battery Charge Level Glitch

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2059]
**Minecraft Version**: 1.18.1
**Forge Version**: 39.0.79+
**Mod Version**: 1.6.12
**Single Player or Server**: Single
**Describe problem (what you were doing; what happened; what should have happened)**:  When creating a "tower" of batteries, with the energy exporting down, and having a battery charging in the bottom battery's slot, the battery charges; however, regardless of whether the batteries are topped up with energy, the "charging" battery will stop at a (seemingly) random number, and refuse to charge further. 

Upon further testing, when this "partly" charged battery is placed, it indicates a full charge. Additionally, when swapped with other partly-charged batteries, this seems to "update" the icon and metadata, indicating a fully charged battery, allowing it to be further stacked with other fully charged batteries. 

**Potentially relevent log snippet:**

`[07:41:00] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.energy.IEnergyStorage.getEnergyStored()" because "handlerHere" is null
	at com.lothrazar.cyclic.block.battery.BlockBattery.m_6240_(BlockBattery.java:68) ~[Cyclic-1.18.1-1.6.12.jar%2355!/:1.18.1-1.6.12]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:254) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2362!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/2045

**Comment by HalcyonSeas73** [comment]
This continues to be an issue in 1.6.13. It seems to be separate from the #2045 issue, in that it doesn't cause a crash, is merely a visual bug. The battery charge level in this photo remains the same, yet after attempting to stack several times with known full batteries, it "updates" its quantity to fully charged, and stacks properly.
![Untitled](https://user-images.githubusercontent.com/84727791/155812663-6124b0b0-0ba2-48a5-bc3f-4d1ed60e3526.png)
