### ISSUE TITLE
Crashes when i attach a fluid pipe to a Deepresonance tank then use wrench on the  pipe

### ISSUE THREAD

**Issue by void513** [PrinceOfAmber/Cyclic#2060]
Minecraft Version: 1.18.1

Forge Version: minecraftforge:39.0.88

Mod Version: Cyclic-1.18.1-1.6.13

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I was trying use drip stone  for inf lava source by let drip into a fluid hopper then use cyclic fluid pipe to send to a DeepResonance tank  but when i attach the pipe to the tank and use a cyclic wrench it crash the game and im unable reenter the world

Log file link:   https://www.pastiebin.com/621da2a0d0694

Video/images/gifs (direct upload or link):

**Comment by void513** [comment]
think this has been fixed deepresonance mod was cause.

**Comment by Lothrazar** [comment]
According to logs bug is caused by deep resonance.  Cyclic uses forge fluid capabilities as normal, but something in the deep resonance "getNetwork" or "getData" area is crashing 

`java.lang.RuntimeException: Don't access this client-side!
	at mcjty.lib.worlddata.AbstractWorldData.getData(AbstractWorldData.java:30) ~[mcjtylib-1.18-6.0.10.jar%23299!/:1.18-6.0.10] {re:classloading}
	at mcjty.deepresonance.modules.tank.data.DRTankNetwork.getNetwork(DRTankNetwork.java:91) ~[deepresonance-3.0.2-beta.jar%23166!/:3.0.2-beta] {re:classloading}
	at mcjty.deepresonance.modules.tank.data.DRTankHandler.getData(DRTankHandler.java:31) ~[deepresonance-3.0.2-beta.jar%23166!/:3.0.2-beta] {re:classloading}
	at mcjty.deepresonance.modules.tank.data.DRTankHandler.getFluidInTank(DRTankHandler.java:42) ~[deepresonance-3.0.2-beta.jar%23166!/:3.0.2-beta] {re:classloading}`
	
	https://github.com/McJtyMods/DeepResonance/issues
