### ISSUE TITLE
Battery breaks without dropping an item

### ISSUE THREAD

**Issue by chokoth** [PrinceOfAmber/Cyclic#2062]
Minecraft Version: 1.18.1

Forge Version: 39.0.79

Mod Version: 1.6.12

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): No matter what Tool I use to break the battery block, it breaks without dropping the item.

Log file link: I pulled this from the server log, it seems to happen ever time I break the block, regardless of tool.

<html>
<body>

[04:38:56] [Server thread/FATAL]: Error executing task on Server
--
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.energy.IEnergyStorage.getEnergyStored()" because "handlerHere" is null
at com.lothrazar.cyclic.block.battery.BlockBattery.m_6240_(BlockBattery.java:68) ~[Cyclic-1.18.1-1.6.12.jar%2354!/:1.18.1-1.6.12]
at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:254) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23114!/:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

</body>
</html>

Video/images/gifs (direct upload or link): None

**Comment by Lothrazar** [comment]
v1.6.13 and has a fix for this
