### ISSUE TITLE
Harvest Syth Critical Error.

### ISSUE THREAD

**Issue by PernDragon** [PrinceOfAmber/Cyclic#2066]
Minecraft Version: 1.18.1

Forge Version: 39.1.1

Mod Version: Latest

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened):
Created item Harvest Syth, Server freaking out and crashes with Error message repeating, and Syth not working.

at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:592) ~[forge-1.18.1-39.0.79-universal.jar%23134!/:?]
        at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%23130!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[server-1.18.1-20211210.034407-srg.jar%23130!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23130!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23130!/:?]

This Message repeats till server Critical Crash.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
According to the log, you're still using 39.0.79, not 39.1.1. Also, what other mods are on the server?

**Comment by Lothrazar** [comment]
this snipped of log doesnt mention cyclic specifically. mod doesnt use the "onPlaceItemIntoWorld" method directly...
are there specific plants it doesnt harvest?, since its all based on data tags

**Comment by PernDragon** [comment]
Mods that have food items I'm running are croptopia, and Quark.  I'll try
the update for Cyclic this week.  Oddly forge isn't showing an update.
