### ISSUE TITLE
compatibility issue with REI 1.18.1

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#2069]
Minecraft Version: 

Forge Version: 39.1.2

Mod Version: Cyclic-1.18.1-1.6.14

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
Attempting to craft biomass using shift click with rei kicks player from server Probably a compatibility issue with
Roughly Enough Items i have to use rei due to another mod in the pack not working with jei on multiplayer.

RoughlyEnoughItems-7.3.443
RoughlyEnoughItems-jei-internals-workaround-7.3.443

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/8193608/latest.log)

**Comment by Lothrazar** [comment]
Seems kind of like maybe a journeymap issue?

`
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Rendersystem called from wrong thread
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at journeymap.client.render.draw.DrawMarkerStep.ensureTexture(DrawMarkerStep.java:120) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.draw.DrawMarkerStep.draw(DrawMarkerStep.java:54) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.map.GridRenderer.draw(GridRenderer.java:444) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.map.GridRenderer.draw(GridRenderer.java:429) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.map.GridRenderer.draw(GridRenderer.java:420) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.ui.fullscreen.Fullscreen.drawMap(Fullscreen.java:1488) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.ui.fullscreen.Fullscreen.m_6305_(Fullscreen.java:438) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:381) ~[forge-1.18.1-39.1.2-universal.jar%23258!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374) ~[forge-1.18.1-39.1.2-universal.jar%23258!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:694) ~[OptiFine_1.18.1_HD_U_H5_MOD.jar%23259!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1276) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.m_187556_(RenderSystem.java:181) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_187555_(RenderSystem.java:159) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.renderer.texture.AbstractTexture.m_117963_(AbstractTexture.java:66) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:106) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:165) ~[client-1.18.1-20211210.034407-srg.jar%23254!/:?]
	at journeymap.client.render.texture.TextureCache.getTexture(TextureCache.java:207) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.draw.DrawMarkerStep$1.call(DrawMarkerStep.java:103) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at journeymap.client.render.draw.DrawMarkerStep$1.call(DrawMarkerStep.java:96) ~[journeymap-1.18.1-5.8.0beta15.jar%23161!/:1.18.1-5.8.0beta15]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:30:56] [Render thread/ERROR]: Error getting MarkerOverlay ima`

Or  harmonized issue ? some snippets from the log there, `java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_6846_()" because the return value of "harmonised.pmmo.pmmo_saved_data.PmmoSavedData.getServer()" is null
	at harmonised.pmmo.skills.Skill.addXp(Skill.java:224) ~[Project_MMO-1.18.1-3.69.9.jar%23201!/:1.18.1-3.69.9]`

**Comment by IchigoGames** [comment]
i thnk its a bug with rei ill report it to them
