### ISSUE TITLE
Crash when using a Monster Ball on Pixelmon Dens (1.12.2) - (Saving entity NBT)

### ISSUE THREAD

**Issue by judgekreep** [PrinceOfAmber/Cyclic#2076]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Mod Version: 1.20.11

Single Player or Server: LAN World

Describe problem (what you were doing; what happened; what should have happened):
I threw a Monster Ball at a Pixelmon Den and the game crashed - this happens rarely, however.
Majority of the time, it captures the Den just fine but sometimes it just crashes.

```
Description: Saving entity NBT

java.lang.NullPointerException: Null string not allowed
    at java.util.Objects.requireNonNull(Objects.java:228)
    at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
    at net.minecraft.nbt.NBTTagCompound.setString(NBTTagCompound.java:138)
    at com.pixelmonmod.pixelmon.entities.npcs.NPCTrainer.writeEntityToNBT(NPCTrainer.java:805)
    at net.minecraft.entity.Entity.writeToNBT(Entity.java:1743)
    at com.lothrazar.cyclicmagic.item.mobcapture.EntityMagicNetEmpty.processImpact(EntityMagicNetEmpty.java:87)
    at com.lothrazar.cyclicmagic.entity.EntityThrowableDispensable.onImpact(EntityThrowableDispensable.java:54)
    at net.minecraft.entity.projectile.EntityThrowable.onUpdate(EntityThrowable.java:249)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zck000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Lothrazar** [comment]
This needs to be fixed on pixelmons side as well they are somehow saving a null string. will be releasing a v1.20.12 version for this too
