### ISSUE TITLE
Shearing Block on Environmental Yak causes crash

### ISSUE THREAD

**Issue by DrUltraLux** [PrinceOfAmber/Cyclic#2105]
Minecraft Version:  1.16.5

Forge Version: 36.2.34

Mod Version:  Cyclic 1.5.15, environmental 1.1.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I placed a Shearing Block into my yak pen, then shearing sound fired, and then the server crashed. 

Log file link:
Will add when I can get it from the server admin

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/environmental/files/3561534

**Comment by Lothrazar** [comment]
Environmental mod needs to do a null check for the NullablePlayer first argument . at com.minecraftabnormals.environmental.common.entity.YakEntity.onSheared(YakEntity.java:227) 

`java.lang.NullPointerException: Colliding entity with block
	at com.minecraftabnormals.environmental.common.entity.YakEntity.onSheared(YakEntity.java:227) ~[?:1.1.1] {re:classloading}
	at com.lothrazar.cyclic.block.shears.BlockShearing.func_196262_a(BlockShearing.java:50) ~[?:1.16.5-1.5.19] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196950_a(AbstractBlock.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:845) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinEntity,pl:mixin:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:597) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2055) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2016) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2451) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,re:mixin}
	at com.minecraftabnormals.environmental.common.entity.YakEntity.func_70636_d(YakEntity.java:119) ~[?:1.1.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:environmental.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$8825/1913944893.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$8472/981254988.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
`
