### ISSUE TITLE
Server Issue 

### ISSUE THREAD

**Issue by Kirisotu** [PrinceOfAmber/Cyclic#2215]
Minecraft Version: 1.19.2

Forge Version: 1.19.2

Mod Version: 1.19.2

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
server crashes every time I explore in new chunk, and the staff of my server cyclic has anti beacon blocks that's messing effects.

Log file link:
at com.lothrazar.cyclic.util.BlockstatesUtil.findBlocks(BlockstatesUtil.java:41) ~[Cyclic-1.19.2-1.7.11.jar%23236!/:1.19.2-1.7.11] {re:classloading}
    at com.lothrazar.cyclic.block.antipotion.BlockAntiBeacon.isPotionApplicable(BlockAntiBeacon.java:114) ~[Cyclic-1.19.2-1.7.11.jar%23236!/:1.19.2-1.7.11] {re:classloading}

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
Try updating Cyclic and Forge? Cyclic latest for 1.19.2 is 1.7.14, you're on 1.7.11. Latest Forge is 43.2.0.
