### ISSUE TITLE
Dotted Key Config Issue

### ISSUE THREAD

**Issue by m4rk34** [PrinceOfAmber/Cyclic#2218]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/28/22 9:00 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9449/1996111320.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9198/181765627.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/253257929.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.3.jar:?] {}
-- MOD cyclic --
Details:
	Mod File: Cyclic-1.16.5-1.5.20.jar
	Failure message: Cyclic (cyclic) has failed to load correctly
		com.electronwill.nightconfig.core.io.ParsingException: Invalid character '
' after key [a]
	Mod Version: 1.16.5-1.5.20
	Mod Issue URL: https://github.com/Lothrazar/cyclic/issues
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Invalid character '
' after key [a]
Stacktrace:
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
	at com.lothrazar.cyclic.config.ConfigRegistry.setup(ConfigRegistry.java:470) ~[?:1.16.5-1.5.20] {re:classloading}
	at com.lothrazar.cyclic.ModCyclic.<init>(ModCyclic.java:31) ~[?:1.16.5-1.5.20] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3165/1175347198.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3323/1692202851.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2098876912 bytes (2001 MB) / 3200253952 bytes (3052 MB) up to 7337410560 bytes (6997 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7872m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		ElenaiDodge-1.16.2-1.7.2.jar                      |Elenai Dodge                  |elenaidodge                   |1.16.2-1.7.2        |CREATE_REG|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0+1.16.5.jar       |Player Animator               |playeranimator                |0.4.0+1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		connectivity-2.4-1.16.5.jar                       |Connectivity Mod              |connectivity                  |2.4-1.16.5          |CREATE_REG|Manifest: NOSIGNATURE
		ContentTweaker-1.16-1.0.0.develop.36.jar          |ContentTweaker                |contenttweaker                |1.0.0.develop.36    |CREATE_REG|Manifest: NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |CREATE_REG|Manifest: NOSIGNATURE
		modnametooltip_1.16.2-1.15.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.15.0              |CREATE_REG|Manifest: NOSIGNATURE
		KleeSlabs_1.16.5-9.2.1.jar                        |KleeSlabs                     |kleeslabs                     |9.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |CREATE_REG|Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |CREATE_REG|Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |CREATE_REG|Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |CREATE_REG|Manifest: NOSIGNATURE
		ultimate_unicorn_mod-1.16.5-1.6.2.jar             |Wings, Horns, and Hooves, the |ultimate_unicorn_mod          |1.6.2               |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		simpleplanes-1.16.5-4.6.0.jar                     |Simple Planes                 |simpleplanes                  |1.16.5-4.6.0        |CREATE_REG|Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |CREATE_REG|Manifest: NOSIGNATURE
		RevampedWolf-1.16.4-0.7.1.jar                     |RevampedWolf                  |revampedwolf                  |1.16.4-0.7.1        |CREATE_REG|Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |CREATE_REG|Manifest: NOSIGNATURE
		toughnessbar-6.1.jar                              |Toughness Bar                 |toughnessbar                  |6.1                 |CREATE_REG|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.16.5.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |CREATE_REG|Manifest: NOSIGNATURE
		ArmorSetBonuses_1.16_V7.jar                       |ArmorSet Bonuses              |spacecatasb                   |1.16 v7             |CREATE_REG|Manifest: NOSIGNATURE
		portablemobs-1.1.1-forge-mc1.16.jar               |Portable Mobs                 |portablemobs                  |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.4.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |CREATE_REG|Manifest: NOSIGNATURE
		CustomNPCs-1.16.5.20220515.jar                    |Custom NPCs                   |customnpcs                    |1.16.5.20220515     |CREATE_REG|Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |CREATE_REG|Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|CREATE_REG|Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |CREATE_REG|Manifest: NOSIGNATURE
		AI-Improvements-1.16.5-0.5.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |CREATE_REG|Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.7.445-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.7.445           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |CREATE_REG|Manifest: NOSIGNATURE
		swem-1.16.5-0.5.3.3.jar                           |Star Worm Equestrian Mod      |swem                          |1.16.5-0.5.3.3      |CREATE_REG|Manifest: NOSIGNATURE
		dungeons_libraries-1.16.5-1.0.2.jar               |Dungeons Libraries            |dungeons_libraries            |1.16.5-1.0.2        |CREATE_REG|Manifest: NOSIGNATURE
		DarkPaintings-1.16.5-6.0.11.jar                   |DarkPaintings                 |darkpaintings                 |6.0.11              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		dungeons_gear-1.16.5-3.2.2.jar                    |Dungeons Gear                 |dungeons_gear                 |1.16.5-3.2.2        |CREATE_REG|Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.20.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.20       |ERROR     |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		ClientTweaks_1.16.3-5.3.0.jar                     |Client Tweaks                 |clienttweaks                  |5.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |CREATE_REG|Manifest: NOSIGNATURE
		ftb-teams-forge-1605.2.3-build.40.jar             |FTB Teams                     |ftbteams                      |1605.2.3-build.40   |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |CREATE_REG|Manifest: NOSIGNATURE
		item-filters-forge-1605.2.5-build.9.jar           |Item Filters                  |itemfilters                   |1605.2.5-build.9    |CREATE_REG|Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		dungeons_mobs-1.16.5-2.2.2.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.16.5-2.2.2        |CREATE_REG|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |CREATE_REG|Manifest: NOSIGNATURE
		configured-1.5.3-1.16.5.jar                       |Configured                    |configured                    |1.5.3               |CREATE_REG|Manifest: NOSIGNATURE
		ItemBorders-1.16.5-1.1.6.jar                      |Item Borders                  |itemborders                   |1.1.6               |CREATE_REG|Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |CREATE_REG|Manifest: NOSIGNATURE
		decorative_winter-0.1.2.jar                       |Decorative Winter             |decorative_winter             |0.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		iceandfire-2.1.11-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |CREATE_REG|Manifest: NOSIGNATURE
		foodeffects-1.16.5-1.0.2.jar                      |Food Effects                  |foodeffects                   |1.0.2               |CREATE_REG|Manifest: NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |CREATE_REG|Manifest: NOSIGNATURE
		ToastControl-1.16.5-4.4.0.jar                     |Toast Control                 |toastcontrol                  |4.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.1.0.49.jar                    |JEI Tweaker                   |jeitweaker                    |1.1.0.49            |CREATE_REG|Manifest: NOSIGNATURE
		EnderStorage-1.16.5-2.8.0.170-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.170           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CraftTweaker-1.16.5-7.1.2.515.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.515           |CREATE_REG|Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.4.0-13.jar            |Immersive Petroleum           |immersivepetroleum            |3.4.0-13            |CREATE_REG|Manifest: NOSIGNATURE
		3dSkinLayers-forge-1.1.0.jar                      |3dSkinLayers                  |skinlayers3d                  |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.5.2.22.jar                     |CoFH Core                     |cofh_core                     |1.5.2.22            |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		ensorcellation-1.16.5-1.5.0.4.jar                 |Ensorcellation                |ensorcellation                |1.5.0.4             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		EnchantmentDescriptions-1.16.5-7.1.20.jar         |EnchantmentDescriptions       |enchdesc                      |7.1.20              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.16-3.1.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.7          |CREATE_REG|Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|Manifest: NOSIGNATURE
		ItemPhysicLite_v1.4.8_mc1.16.5.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|Manifest: NOSIGNATURE
		ftb-quests-forge-1605.3.6-build.98.jar            |FTB Quests                    |ftbquests                     |1605.3.6-build.98   |CREATE_REG|Manifest: NOSIGNATURE
		ftb-money-1605.1.4-build.9.jar                    |FTB Money                     |ftbmoney                      |1605.1.4-build.9    |CREATE_REG|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |CREATE_REG|Manifest: NOSIGNATURE
		ImmersiveIndustry-1.16.5-0.1.8e.jar               |Immersive Industry            |immersiveindustry             |1.16.5-0.1.8e       |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|Manifest: NOSIGNATURE
		archers_paradox-1.16.5-1.5.0.2.jar                |Archer's Paradox              |archers_paradox               |1.5.0.2             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		CreateTweaker-1.0.0.26.jar                        |CreateTweaker                 |createtweaker                 |1.0.0.26            |CREATE_REG|Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		car-1.16.5-1.0.17.jar                             |Ultimate Car Mod              |car                           |1.16.5-1.0.17       |CREATE_REG|Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.1.0.22.jar                |JEI Integration               |jeiintegration                |7.1.0.22            |CREATE_REG|Manifest: NOSIGNATURE
		Iceberg-1.16.5-1.0.45.jar                         |Iceberg                       |iceberg                       |1.0.45              |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |CREATE_REG|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|Manifest: NOSIGNATURE
		MorePlayerModels-1.16.5.20220731.jar              |More Player Models            |moreplayermodels              |1.16.5.20220731     |CREATE_REG|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |CREATE_REG|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|Manifest: NOSIGNATURE
		Quark-r2.4-322.jar                                |Quark                         |quark                         |r2.4-322            |CREATE_REG|Manifest: NOSIGNATURE
		entityculling-forge-mc1.16.5-1.5.2.jar            |EntityCulling                 |entityculling                 |1.5.2               |CREATE_REG|Manifest: NOSIGNATURE
		swiaf-1.16.5-1.1.2.jar                            |Spartan Weaponry: Ice and Fire|swiaf                         |1.16.5-1.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |CREATE_REG|Manifest: NOSIGNATURE
		bloodandgore-1.16.5-v1.1.jar                      |Blood and Gore                |blood_and_gore                |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |CREATE_REG|Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |CREATE_REG|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		createaddition-1.16.5-20220129a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20220129a    |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 73cd5844-566b-4d93-b3ce-ac980c3714d4
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.30.22 30.0.13022.3
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by Mrbysco** [comment]
Did you change the config? if not try deleting the config to have it generate fresh

**Comment by Lothrazar** [comment]
as stated above you have invalid quotes in the config file, its a very strict format.  Either fix the syntax or delete the config fully and it will generate a valid one
