### ISSUE TITLE
Custom Modpack Server Crashing Issue

### ISSUE THREAD

**Issue by KrispKlank** [PrinceOfAmber/Cyclic#2302]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Mod Version: 1.20.14

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I was playing a custom modpack with some friends and Cyclic ran into an issue with the mod Arcane World [Mod Version: 0.0.11]. It causes the server to crash every time a player loads the chunk that the error occurred in. I don't have much information as I wasn't even looking at any of my places cyclic blocks the first time the crash happened. The crashing persists even after the server starts back up again.

Log file link:

[Crash Report.txt](https://github.com/Lothrazar/Cyclic/files/12137964/Crash.Report.txt)

Video/images/gifs (direct upload or link): 

N/A

**Comment by Lothrazar** [comment]
cyclic in 1.12.2 has been run on many servers without this issue, but if im wrong and cyclic needs an update i can do one. however, Based on this changelog, it appears that the arcane mod is trying to load a client-side-only methods on the server.  Some problem with the ItemRitualScroll.  
So i think that mod needs to update.  
```
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at party.lemons.arcaneworld.item.impl.ItemRitualScroll.func_77653_i(ItemRitualScroll.java:87)
```
Also it looks like this hammercore mod is forcing the cylcic Cables to tick (which means do work) all the time as long as the chunk is loaded, idk if thats related '  at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)'

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/arcane-world/files?version=1.12.2 happens when ItemRitualScroll is in inside an item pipe moving around while chunk loads/unloads

**Comment by Lothrazar** [comment]
as per the previous comments, this has been solved by finding the actual root cause. closing as there have been no updates since then.  

we are keeping 1.12.2 stable outside of emergency fixes. 

as always new issue reports are welcome
