### ISSUE TITLE
Crashing whenever I add to a modpack

### ISSUE THREAD

**Issue by JohnBon315** [PrinceOfAmber/Cyclic#2354]
Minecraft Version: 1.20.1

Forge Version: 1.20.1

Mod Version: 1.20.1

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

well whenever I try to start a world with the mod it keeps crashing me, I'm trying to add the mod so it is easier to clear land and or build. But before i updated the mod pack i added it in it was fine but then i updated and tis crashing my game each time i try to play

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
can i see the crash log to see which mod and/or block and/or entity and/or item is causing the crash?

**Comment by JohnBon315** [comment]
Time: 2024-01-03 16:51:28
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved
sources: [Reference{ResourceKey[minecraft:worldgen/biome /
***@***.***},
Reference{ResourceKey[minecraft:worldgen/biome /
***@***.***}]
at
net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
net.minecraft.world.level.chunk.ChunkGenerator.m_223094_(ChunkGenerator.java:102)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:gtceu-common.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
at
com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
~[guava-31.1-jre.jar%23109!/:?] {}
at
net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:288)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:gtceu-common.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
at
net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
at
net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
at
net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
~[datafixerupper-6.0.8.jar%23114!/:?] {}
at
net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?]
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at
java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
~[?:?] {}
at
java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
~[?:?] {}
at
net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
~[client-1.20.1-20230612.114412-srg.jar%23980!/:?] {re:classloading}
at
java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
~[?:?] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
at
java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
~[?:?] {}
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
{re:mixin,re:computing_frames}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
~[?:?] {re:mixin,re:computing_frames}
at
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
~[?:?] {re:mixin}

**Comment by babamonk09** [comment]
I'm having the same problem with the same version, it won't let me create a new world with cyclic in the mod list since it crashes the game while loading in the chunks, and when i'm in another world that was created without cyclic at first, and I try to load new chunks while cyclic is on, then it also crashes my game.

**Comment by CraftyZombie** [comment]
Since this is chunk-loading related, I'm guessing it's a replicate of https://github.com/Lothrazar/Cyclic/issues/2332. 

Cyclic Crash Fixer (https://modrinth.com/mod/cyclic-crash-fixer) may help fix your problem in the meantime.

**Comment by JohnBon315** [comment]
Yup that worked thanks for the mod, it stopped the crashing
