### ISSUE TITLE
Crash on Pickup Opened Bag

### ISSUE THREAD

**Issue by MurphysChaos** [PrinceOfAmber/Cyclic#319]
When looking at an opened ItemStorageBag, if you click on the bag itself, the client will crash. Crash report follows.

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/25/17 5:37 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.network.play.client.CPacketClickWindow.<init>(CPacketClickWindow.java:37)
	at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:593)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:687)
	at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:429)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1792)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.run(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.network.play.client.CPacketClickWindow.<init>(CPacketClickWindow.java:37)
	at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:593)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:687)
	at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:429)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)

-- Affected screen --
Details:
	Screen name: com.lothrazar.cyclicmagic.gui.storage.GuiStorage

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player482'/53, l='MpServer', x=-1599.43, y=139.00, z=-629.74]]
	Chunk stats: MultiplayerChunkCache: 607, 607
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-175,64,237), Chunk: (at 1,4,13 in -11,14; contains blocks -176,0,224 to -161,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 16599 game time, 16599 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 116 total; [EntityPlayerSP['Player482'/53, l='MpServer', x=-1599.43, y=139.00, z=-629.74], EntityChicken['Chicken'/301, l='MpServer', x=-1537.13, y=80.00, z=-656.51], EntityChicken['Chicken'/302, l='MpServer', x=-1540.23, y=80.00, z=-656.12], EntityZombie['Zombie'/305, l='MpServer', x=-1545.24, y=89.00, z=-684.55], EntitySkeleton['Skeleton'/306, l='MpServer', x=-1550.50, y=87.00, z=-679.50], EntitySkeleton['Skeleton'/307, l='MpServer', x=-1543.50, y=89.00, z=-687.50], EntityChicken['Chicken'/308, l='MpServer', x=-1561.50, y=109.00, z=-667.50], EntityChicken['Chicken'/309, l='MpServer', x=-1562.50, y=109.00, z=-667.50], EntityItem['item.tile.oreIron'/54, l='MpServer', x=-1594.11, y=139.00, z=-627.41], EntitySkeleton['Skeleton'/310, l='MpServer', x=-1562.50, y=109.00, z=-668.50], EntityChicken['Chicken'/311, l='MpServer', x=-1564.12, y=112.00, z=-664.62], EntityChicken['Chicken'/312, l='MpServer', x=-1567.18, y=114.00, z=-661.50], EntityZombie['Zombie'/320, l='MpServer', x=-1581.50, y=80.00, z=-658.50], EntitySkeleton['Skeleton'/321, l='MpServer', x=-1568.82, y=113.00, z=-666.50], EntityChicken['Chicken'/326, l='MpServer', x=-1532.77, y=80.00, z=-648.45], EntityChicken['Chicken'/327, l='MpServer', x=-1533.50, y=80.00, z=-649.50], EntityChicken['Chicken'/328, l='MpServer', x=-1528.22, y=80.00, z=-653.60], EntityChicken['Chicken'/330, l='MpServer', x=-1551.50, y=107.00, z=-639.50], EntityZombie['Zombie'/331, l='MpServer', x=-1561.81, y=79.00, z=-610.51], EntityBat['Bat'/332, l='MpServer', x=-1574.47, y=34.06, z=-590.16], EntityChicken['Chicken'/333, l='MpServer', x=-1569.50, y=113.00, z=-603.50], EntityChicken['Chicken'/334, l='MpServer', x=-1568.50, y=114.00, z=-604.50], EntityChicken['Chicken'/335, l='MpServer', x=-1570.50, y=116.00, z=-606.50], EntitySkeleton['Skeleton'/336, l='MpServer', x=-1575.50, y=113.00, z=-600.50], EntityChicken['Chicken'/338, l='MpServer', x=-1526.51, y=77.00, z=-671.93], EntityChicken['Chicken'/339, l='MpServer', x=-1520.87, y=79.00, z=-668.45], EntitySpider['Spider'/340, l='MpServer', x=-1521.50, y=79.00, z=-670.50], EntityChicken['Chicken'/341, l='MpServer', x=-1537.50, y=80.00, z=-649.50], EntityChicken['Chicken'/342, l='MpServer', x=-1549.49, y=95.00, z=-644.17], EntityChicken['Chicken'/343, l='MpServer', x=-1550.50, y=106.00, z=-641.50], EntityChicken['Chicken'/344, l='MpServer', x=-1551.50, y=107.00, z=-641.50], EntityItem['item.item.leather'/345, l='MpServer', x=-1553.71, y=28.00, z=-626.66], EntityZombie['Zombie'/346, l='MpServer', x=-1565.50, y=85.00, z=-625.50], EntityChicken['Chicken'/347, l='MpServer', x=-1565.80, y=120.00, z=-630.57], EntityChicken['Chicken'/348, l='MpServer', x=-1565.15, y=121.00, z=-633.47], EntityChicken['Chicken'/349, l='MpServer', x=-1567.54, y=123.00, z=-636.23], EntitySkeleton['Skeleton'/350, l='MpServer', x=-1576.51, y=90.00, z=-616.21], EntitySkeleton['Skeleton'/351, l='MpServer', x=-1577.22, y=86.00, z=-610.54], EntityChicken['Chicken'/352, l='MpServer', x=-1573.27, y=119.00, z=-611.13], EntitySkeleton['Skeleton'/355, l='MpServer', x=-1522.50, y=79.00, z=-622.50], EntityChicken['Chicken'/356, l='MpServer', x=-1546.50, y=84.00, z=-606.50], EntityChicken['Chicken'/357, l='MpServer', x=-1548.52, y=89.00, z=-601.87], EntityChicken['Chicken'/358, l='MpServer', x=-1547.50, y=86.00, z=-604.50], EntityChicken['Chicken'/359, l='MpServer', x=-1551.48, y=85.00, z=-602.88], EntityZombie['Zombie'/360, l='MpServer', x=-1569.24, y=49.00, z=-575.53], EntityBat['Bat'/361, l='MpServer', x=-1578.49, y=38.73, z=-576.34], EntityBat['Bat'/363, l='MpServer', x=-1571.25, y=45.10, z=-580.56], EntitySkeleton['Skeleton'/364, l='MpServer', x=-1569.50, y=43.00, z=-578.50], EntityCreeper['Creeper'/365, l='MpServer', x=-1568.50, y=44.00, z=-580.16], EntityBat['Bat'/366, l='MpServer', x=-1571.71, y=40.06, z=-574.12], EntityBat['Bat'/367, l='MpServer', x=-1569.75, y=32.10, z=-584.75], EntityBat['Bat'/368, l='MpServer', x=-1573.44, y=34.93, z=-580.73], EntityBat['Bat'/369, l='MpServer', x=-1575.50, y=39.21, z=-571.54], EntityCreeper['Creeper'/370, l='MpServer', x=-1571.50, y=42.00, z=-581.50], EntitySkeleton['Skeleton'/371, l='MpServer', x=-1569.56, y=50.00, z=-583.42], EntitySkeleton['Skeleton'/372, l='MpServer', x=-1568.37, y=50.00, z=-583.75], EntitySkeleton['Skeleton'/373, l='MpServer', x=-1575.50, y=49.00, z=-589.50], EntityCreeper['Creeper'/374, l='MpServer', x=-1576.50, y=49.00, z=-589.50], EntityCreeper['Creeper'/129, l='MpServer', x=-1672.46, y=80.00, z=-677.20], EntityCreeper['Creeper'/131, l='MpServer', x=-1673.54, y=56.00, z=-614.40], EntityZombie['Zombie'/387, l='MpServer', x=-1555.45, y=81.00, z=-585.27], EntityBat['Bat'/388, l='MpServer', x=-1553.36, y=41.21, z=-569.42], EntityCreeper['Creeper'/132, l='MpServer', x=-1678.47, y=57.00, z=-611.76], EntitySpider['Spider'/133, l='MpServer', x=-1674.06, y=56.00, z=-618.00], EntityZombie['Zombie'/389, l='MpServer', x=-1562.80, y=49.00, z=-574.51], EntityZombie['Zombie'/134, l='MpServer', x=-1667.75, y=79.00, z=-626.69], EntityChicken['Chicken'/136, l='MpServer', x=-1668.50, y=96.00, z=-570.50], EntityChicken['Chicken'/137, l='MpServer', x=-1667.50, y=99.00, z=-570.50], EntityChicken['Chicken'/138, l='MpServer', x=-1666.50, y=99.00, z=-573.50], EntityCreeper['Creeper'/145, l='MpServer', x=-1674.50, y=79.00, z=-626.50], EntityCreeper['Creeper'/159, l='MpServer', x=-1645.80, y=79.00, z=-687.51], EntityBat['Bat'/927, l='MpServer', x=-1646.38, y=60.03, z=-604.25], EntityBat['Bat'/928, l='MpServer', x=-1641.05, y=60.32, z=-607.63], EntityCreeper['Creeper'/163, l='MpServer', x=-1644.49, y=79.00, z=-687.22], EntityChicken['Chicken'/165, l='MpServer', x=-1632.50, y=82.00, z=-637.50], EntityChicken['Chicken'/166, l='MpServer', x=-1634.50, y=84.00, z=-637.50], EntityBat['Bat'/167, l='MpServer', x=-1653.71, y=36.99, z=-607.43], EntityZombie['Zombie'/169, l='MpServer', x=-1651.50, y=61.00, z=-608.50], EntityChicken['Chicken'/172, l='MpServer', x=-1657.50, y=77.00, z=-652.50], EntityChicken['Chicken'/173, l='MpServer', x=-1656.50, y=76.00, z=-648.50], EntityZombie['Zombie'/174, l='MpServer', x=-1652.49, y=72.00, z=-651.24], EntityChicken['Chicken'/175, l='MpServer', x=-1658.50, y=83.00, z=-654.50], EntityChicken['Chicken'/176, l='MpServer', x=-1656.50, y=83.00, z=-653.50], EntityBat['Bat'/177, l='MpServer', x=-1628.75, y=55.10, z=-616.25], EntityBat['Bat'/178, l='MpServer', x=-1633.43, y=52.55, z=-600.93], EntityChicken['Chicken'/179, l='MpServer', x=-1651.46, y=90.00, z=-590.89], EntityChicken['Chicken'/180, l='MpServer', x=-1629.54, y=77.00, z=-625.79], EntityBat['Bat'/181, l='MpServer', x=-1658.45, y=37.09, z=-606.23], EntityChicken['Chicken'/182, l='MpServer', x=-1645.87, y=90.00, z=-591.85], EntityChicken['Chicken'/183, l='MpServer', x=-1650.04, y=90.00, z=-596.76], EntityChicken['Chicken'/184, l='MpServer', x=-1651.50, y=90.00, z=-596.50], EntityZombie['Zombie'/185, l='MpServer', x=-1653.22, y=80.00, z=-596.34], EntityChicken['Chicken'/186, l='MpServer', x=-1627.76, y=84.00, z=-641.50], EntityZombie['Zombie'/187, l='MpServer', x=-1657.50, y=101.00, z=-547.50], EntitySkeleton['Skeleton'/188, l='MpServer', x=-1628.50, y=51.00, z=-603.50], EntitySkeleton['Skeleton'/189, l='MpServer', x=-1631.50, y=51.00, z=-601.50], EntityChicken['Chicken'/190, l='MpServer', x=-1657.84, y=100.00, z=-574.60], EntityCreeper['Creeper'/191, l='MpServer', x=-1655.51, y=99.00, z=-575.68], EntitySkeleton['Skeleton'/192, l='MpServer', x=-1624.50, y=86.00, z=-549.50], EntityCreeper['Creeper'/211, l='MpServer', x=-1608.77, y=109.00, z=-700.50], EntityChicken['Chicken'/213, l='MpServer', x=-1609.36, y=77.00, z=-632.07], EntityBat['Bat'/214, l='MpServer', x=-1589.41, y=58.40, z=-646.26], EntityChicken['Chicken'/215, l='MpServer', x=-1610.45, y=77.00, z=-620.37], EntityChicken['Chicken'/216, l='MpServer', x=-1614.50, y=77.00, z=-620.50], EntityChicken['Chicken'/217, l='MpServer', x=-1613.16, y=77.00, z=-620.52], EntitySkeleton['Skeleton'/218, l='MpServer', x=-1601.79, y=96.00, z=-555.50], EntityZombie['Zombie'/228, l='MpServer', x=-1676.50, y=85.00, z=-662.50], EntityCreeper['Creeper'/233, l='MpServer', x=-1584.56, y=102.00, z=-671.86], EntityZombie['Zombie'/234, l='MpServer', x=-1596.64, y=79.00, z=-615.77], EntityZombie['Zombie'/235, l='MpServer', x=-1596.50, y=79.00, z=-614.50], EntityChicken['Chicken'/236, l='MpServer', x=-1593.51, y=136.00, z=-622.52], EntityZombie['Zombie'/237, l='MpServer', x=-1597.50, y=89.00, z=-586.50], EntityBat['Bat'/238, l='MpServer', x=-1594.43, y=25.02, z=-597.84], EntitySkeleton['Skeleton'/239, l='MpServer', x=-1585.50, y=63.00, z=-553.50], EntityCreeper['Creeper'/240, l='MpServer', x=-1585.50, y=87.00, z=-572.50], EntityItem['item.item.leather'/767, l='MpServer', x=-1554.56, y=28.00, z=-628.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:451)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2774)
	at net.minecraft.client.Minecraft.run(Minecraft.java:428)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264655896 bytes (252 MB) / 1828716544 bytes (1744 MB) up to 7607943168 bytes (7255 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2252 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.11.2-13.20.0.2252-PROJECT(Cyclic).jar) 
	UCHIJAAAA	forge{13.20.0.2252} [Minecraft Forge] (forgeSrc-1.11.2-13.20.0.2252-PROJECT(Cyclic).jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	jei{4.2.8.244} [Just Enough Items] (jei_1.11.2-4.2.8.244.jar) 
	UCHIJAAAA	cyclicmagic{1.2.3} [Cyclic] (Cyclic-1.11.2-1.2.3.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: 1.11.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
```

**Comment by PrinceOfAmber** [comment]
Yep thats my screen, Screen name: com.lothrazar.cyclicmagic.gui.storage.GuiStorage

But its weird that within the java.lang.NullPointerException theres no line number for me.

**Comment by PrinceOfAmber** [comment]
This should fix it, let me know if theres any other issues.

https://minecraft.curseforge.com/projects/cyclic/files/2397431
