### ISSUE TITLE
Block Miner

### ISSUE THREAD

**Issue by HeroicConcept** [PrinceOfAmber/Cyclic#328]
Everytime I use it my game crashes when I add a redstone signal to it.

**Comment by PrinceOfAmber** [comment]
Could be an issue here. can you post your log file next time it crashes? Should be in your minecraft folder so minecraft/logs/latest.log

**Comment by PrinceOfAmber** [comment]
NVM looks like i replicated the same issue that you found


on thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(TileEntityRendererDispatcher.java:163) ~[TileEntityRendererDispatcher.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(TileEntityRendererDispatcher.java:131) ~[TileEntityRendererDispatcher.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:723) ~[RenderGlobal.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1389) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1303) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1106) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:407) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at com.lothrazar.cyclicmagic.block.tileentity.MachineTESR.render(MachineTESR.java:26) ~[MachineTESR.class:?]
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.renderTileEntityAt(BaseMachineTesr.java:79) ~[BaseMachineTesr.class:?]
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.renderTileEntityAt(BaseMachineTesr.java:1) ~[BaseMachineTesr.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(TileEntityRendererDispatcher.java:156) ~[TileEntityRendererDispatcher.class:?]
	... 20 more
[00:31:20] [Server thread/INFO] [FML]: Applying holder lookups
[00:31:20] [Server thread/INFO] [FML]: Holder lookups applied
[00:31:20] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/1/17 12:31 AM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.lothrazar.cyclicmagic.block.tileentity.MachineTESR.render(MachineTESR.java:26)
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.renderTileEntityAt(BaseMachineTesr.java:79)
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.renderTileEntityAt(BaseMachineTesr.java:1)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:723)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1389)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1303)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1106)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140)
	at net.minecraft.client.Minecraft.run(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

**Comment by PrinceOfAmber** [comment]
Probable duplciate of https://github.com/PrinceOfAmber/Cyclic/issues/331

**Comment by PrinceOfAmber** [comment]
Uploaded a fix here . if this link doesnt work check again later, curse takes a minute to update and sync across network https://minecraft.curseforge.com/projects/cyclic/files/2401197
