### ISSUE TITLE
[1.11.2] infrequent crash when a machine is running and an unloaded chunk loads in again

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#331]
[00:07:06] [Server thread/INFO]: Unloading dimension 1
[00:07:08] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:181) ~[bsk.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:145) ~[bsk.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:998) ~[bqm.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757) ~[bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582) ~[bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1359) ~[bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.lothrazar.cyclicmagic.block.tileentity.MachineTESR.render(MachineTESR.java:26) ~[MachineTESR.class:?]
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.renderTileEntityAt(BaseMachineTesr.java:79) ~[BaseMachineTesr.class:?]
	at com.lothrazar.cyclicmagic.block.tileentity.BaseMachineTesr.func_180535_a(BaseMachineTesr.java:33) ~[BaseMachineTesr.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:172) ~[bsk.class:?]

**Comment by PrinceOfAmber** [comment]
Closed as duplicate
