### ISSUE TITLE
[1.11.2] Crash when using MouseTweaks combined with the 3x3 inventory cake grid and dragging items

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#338]
-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at **com.lothrazar.cyclicmagic.gui.playerworkbench.InventoryPlayerExtWorkbench.func_70299_a(InventoryPlayerExtWorkbench.java:90)
	at com.lothrazar.cyclicmagic.gui.playerworkbench.InventoryPlayerExtWorkbench.func_70298_a(InventoryPlayerExtWorkbench.java:51)**
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:98)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:296)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:548)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)

**Comment by PrinceOfAmber** [comment]
Fixed https://minecraft.curseforge.com/projects/cyclic/files/2408795
