### ISSUE TITLE
Garden scythe crashes when harvesting Experience Crops from Giacomo's mod

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#362]
this mod https://mods.curse.com/mc-mods/minecraft/230553-giacomos-experience-seedling 

[17:33:31] [Client thread/FATAL]: Unreported exception thrown!
java.lang.RuntimeException: call getDrops
	at com.polipo.exp.BlockExpPlant.func_180660_a(BlockExpPlant.java:237) ~[BlockExpPlant.class:?]
	at com.lothrazar.cyclicmagic.util.UtilHarvestCrops.harvestSingle(UtilHarvestCrops.java:210) ~[UtilHarvestCrops.class:?]
	at com.lothrazar.cyclicmagic.util.UtilHarvestCrops.harvestArea(UtilHarvestCrops.java:68) ~[UtilHarvestCrops.class:?]
	at com.lothrazar.cyclicmagic.item.tool.ItemToolHarvest.func_180614_a(ItemToolHarvest.java:58) ~[ItemToolHarvest.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:166) ~[afj.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:462) ~[bnp.class:?]
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87) ~[PlayerControllerOF.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:33:32] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IMLoadingPlugin (infinimend-1.11.2-1.0.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  CreativePatchingLoader (CreativeCore v1.7.3 mc1.11.2.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.8.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  This Coremod Fixed MC-2518 (Fix MC-2518.jar)
  BIFLoader (BowInfinityFix-1.11.x-rv4.jar)
  LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  Augmented Interactions (auginter-1.0.0-1.11.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/30/17 5:33 PM
Description: Unexpected error

java.lang.RuntimeException: call getDrops
	at com.polipo.exp.BlockExpPlant.func_180660_a(BlockExpPlant.java:237)
	at com.lothrazar.cyclicmagic.util.UtilHarvestCrops.harvestSingle(UtilHarvestCrops.java:210)
	at com.lothrazar.cyclicmagic.util.UtilHarvestCrops.harvestArea(UtilHarvestCrops.java:68)
	at com.lothrazar.cyclicmagic.item.tool.ItemToolHarvest.func_180614_a(ItemToolHarvest.java:58)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:166)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:462)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2414355
