### ISSUE TITLE
Automatic fishing net make crashing when a fishing rod is inserted inside

### ISSUE THREAD

**Issue by The-Brook** [PrinceOfAmber/Cyclic#393]
Last version : 1.11.2_1.5.1

**Comment by PrinceOfAmber** [comment]
Yep when i used shift-click this happened

java.util.IllegalFormatConversionException: f != java.lang.Integer
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2806)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2753)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at com.lothrazar.cyclicmagic.component.fisher.GuiFisher.func_146979_b(GuiFisher.java:44)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:118)
	at com.lothrazar.cyclicmagic.gui.GuiBaseContainer.func_73863_a(GuiBaseContainer.java:161)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:530)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

**Comment by PrinceOfAmber** [comment]
Patch is live! https://minecraft.curseforge.com/projects/cyclic/files/2430067
