### ISSUE TITLE
1.12 Server not starting up here's a crash report.

### ISSUE THREAD

**Issue by PoisonPixel** [PrinceOfAmber/Cyclic#408]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.0.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.0.jar)
  FCFMLCorePlugin (FinderCompass-1.12.jar)
  LoadingPlugin (Quark-r1.2-96.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/19/17 1:56 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cyclic (cyclicmagic)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:83)
	at com.lothrazar.cyclicmagic.registry.EventRegistry.registerAll(EventRegistry.java:26)
	at com.lothrazar.cyclicmagic.ModCyclic.onInit(ModCyclic.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:830)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:216)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 243218136 bytes (231 MB) / 426835968 bytes (407 MB) up to 1042022400 bytes (993 MB)
	JVM Flags: 1 total; -Xmx1028M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2334 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHI	forge{14.21.0.2334} [Minecraft Forge] (forge.jar) 
	UCHI	uncraftingtable{1.8-beta2} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta2.jar) 
	UCHI	actuallyadditions{1.12-r111} [Actually Additions] (ActuallyAdditions-1.12-r111.jar) 
	UCHI	thedragonlib{1.12-4.0.0} [TheDragonLib] (thedragonlib-1.12-4.0.0.jar) 
	UCHI	armorplus{1.12-11.0.1.2-alpha} [ArmorPlus] (armorplus-1.12-11.0.1.2-alpha.jar) 
	UCHI	quark{r1.2-96} [Quark] (Quark-r1.2-96.jar) 
	UCHI	autoreglib{1.2-8} [AutoRegLib] (AutoRegLib-1.2-8.jar) 
	UCHI	chesttransporter{2.8.1} [Chest Transporter] (ChestTransporter-1.12-2.8.1.jar) 
	UCHI	cxlibrary{1.5.0} [CXLibrary] (cxlibrary-1.12-1.5.0.jar) 
	UCHI	jei{4.6.0.63} [Just Enough Items] (jei_1.12-4.6.0.63.jar) 
	UCHE	cyclicmagic{1.5.6} [Cyclic] (Cyclic-1.12-1.5.6.jar) 
	UCHI	quickleafdecay{1.2.3} [Quick Leaf Decay] (FastLeafDecay-Mod-1.12.jar) 
	UCHI	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.12.jar) 
	UCHI	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHI	waila{1.8.18} [Waila] (Hwyla-1.8.18-B32_1.12.jar) 
	UCHI	magicalmap{2.1.0} [Magical Map] (Magical Map-1.12-2.1.0.jar) 
	UCHI	morefurnaces{1.10.0} [More Furnaces] (MoreFurnaces-1.12-1.10.0.jar) 
	UCHI	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-Mod-1.12.jar) 
	UCHI	mycommands{1.12-01} [MY Commands] (MyCommands-1.12-01.jar) 
	UCHI	oreexcavation{1.4.96} [OreExcavation] (OreExcavation-1.4.96.jar) 
	UCHI	refinedstorage{1.5} [Refined Storage] (refinedstorage-1.5.jar) 
	UCHI	simplegrinder{4.015.A112} [Simple Grinder] (SimpleGrinder-4.012.A112.jar) 
	UCHI	tse{v1.0.6.10-1.12} [The Stuff Extension] (tse-v1.0.6.10-1.12.jar) 
	UCHI	wholetreeaxe{1.7.0} [Whole Tree Axe] (Whole-Tree-Axe-Mod-1.12.jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.0.jar)
  
CXLibraryCore (cxlibrary-1.12-1.5.0.jar)
  cubex2.cxlibrary.CoreModTransformer
FCFMLCorePlugin (FinderCompass-1.12.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
LoadingPlugin (Quark-r1.2-96.jar)
  vazkii.quark.base.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PrinceOfAmber** [comment]
Thanks for the report, new minecraft versions are always rough at first.

**Comment by PoisonPixel** [comment]
The new version is working great. Thanks for all your hard work!!
