### ISSUE TITLE
[1.11.2] Crash when opening chisel & bits bag

### ISSUE THREAD

**Issue by Andronomos** [PrinceOfAmber/Cyclic#410]
If I open up a bit bag then right click anywhere inside it, the game crashes.

Using Cyclic-1.11.2-1.5.6 and chiselsandbits-13.11

**Main error**

> -- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:114)
	at com.lothrazar.cyclicmagic.event.EventKeyInput.onMouseEvent(EventKeyInput.java:119)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_EventKeyInput_onMouseEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:511)
-- Affected screen --
Details:
	Screen name: mod.chiselsandbits.bitbag.BagGui

**Full Log**
https://pastebin.com/zd3SKqj3

**Installed Mods**
https://pastebin.com/iewAfs51

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2440014

**Comment by Andronomos** [comment]
It felt really satisfying to know I helped make the mod better.
