### ISSUE TITLE
1.12 Missing Recipes

### ISSUE THREAD

**Issue by revdave33** [PrinceOfAmber/Cyclic#437]
Minecraft version & Mod Version: 1.12
MCP 9.40
Forge 14.21.1.2406
Cyclic-1.12-1.5.11.jar

Single player

Describe problem (what you were doing / what happened):
Went to craft any one of the Charms, They show up in jei, but no recipe appears when choosing one.
Same thing with Empty Sack of Holding. I can choose it on jei, but no recipe is suggested.

**Comment by PrinceOfAmber** [comment]
Yes there is a bug in forge when using JSON recipes.

If you disable any of the cyclic items in config file, such as in the  "content" section of the config file, if any of those are false, then forge has an error when trying to load all the recipes from cyclic.

It basically stops at that missing item and unloads all recipes instead of just unloading that one. Same thing happened this morning on a server iplay on 

 Somewhere in one of your log files it will do this


com.google.gson.JsonSyntaxException: Unknown item 'cyclicmagic:uncrafting_block'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:211) ~[CraftingHelper.class:?]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:238) ~[ShapedOreRecipe.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:402) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$21(CraftingHelper.java:702) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:790) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:659) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_111]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:614) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]


Working on a fix soon.  ... BUT For the short term you can just delete the config file, or turn those back on, and recipes SHOULD come back when you restart the game.

**Comment by revdave33** [comment]
Ummm, that didn't work and I am not seeing those lines in my log file. Attached is the latest log file. You will note that I had previously used a lower version in order to craft the charms and EmptySack. They are still there, I just can't make any new ones.
[latest.log.txt](https://github.com/PrinceOfAmber/Cyclic/files/1140407/latest.log.txt)

**Comment by revdave33** [comment]
Latest update fixed this. Thank you
