### ISSUE TITLE
Missing Container displayName

### ISSUE THREAD

**Issue by phit** [PrinceOfAmber/Cyclic#517]
Minecraft version & Mod Version:
1.12.2 Cyclic-1.12-1.8.6.jar

Describe problem (what you were doing / what happened):
You aren't setting displayName, which ideally should never happen

```
03.10 15:41:30 [Server] Netty Epoll Server IO #1/WARN [Sponge]: AbstractMethodError! Could not find displayName for com.lothrazar.cyclicmagic.component.playerext.storage.InventoryPlayerExtended 
03.10 15:41:30 [Server] INFO java.lang.AbstractMethodError: null 
03.10 15:41:30 [Server] INFO at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.getFirstDisplayName(ContainerFabric.java:124) [ContainerFabric.class:1.12.2-2486-7.0.0-BETA-2684] 
03.10 15:41:30 [Server] INFO at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.<init>(ContainerFabric.java:49) [ContainerFabric.class:1.12.2-2486-7.0.0-BETA-2684] 
03.10 15:41:30 [Server] INFO at org.spongepowered.common.item.inventory.lens.impl.MinecraftFabric.of(MinecraftFabric.java:52) [MinecraftFabric.class:1.12.2-2486-7.0.0-BETA-2684] 
03.10 15:41:30 [Server] INFO at net.minecraft.inventory.Container.init(Container.java:965) [afr.class:?] 
03.10 15:41:30 [Server] INFO at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1023) [afr.class:?] 
03.10 15:41:30 [Server] INFO at net.minecraft.inventory.Container.func_75142_b(Container.java:1017) [afr.class:?] 
03.10 15:41:30 [Server] INFO at net.minecraft.inventory.Container.func_75132_a(Container.java:1004) [afr.class:?] 
03.10 15:41:30 [Server] INFO at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) [FMLNetworkHandler.class:?] 
03.10 15:41:30 [Server] INFO at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2546) [aed.class:?] 
03.10 15:41:30 [Server] INFO at com.lothrazar.cyclicmagic.component.playerext.PacketOpenExtendedInventory.onMessage(PacketOpenExtendedInventory.java:17) [PacketOpenExtendedInventory.class:?] 
03.10 15:41:30 [Server] INFO at com.lothrazar.cyclicmagic.component.playerext.PacketOpenExtendedInventory.onMessage(PacketOpenExtendedInventory.java:9) [PacketOpenExtendedInventory.class:?] 
...
```

**Comment by PrinceOfAmber** [comment]
This should fix it, at least i fixed wherever it was doing that for the logs.  

But i havent used sponge before so let me know :) https://minecraft.curseforge.com/projects/cyclic/files/2487756
