### ISSUE TITLE
Scaffolding: crashes on playing sound. i had ambience , soundfilters , and dynamic surroundings installed

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#54]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  LoadingPlugin (Quark-beta-44.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.7.0.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 17/07/16 6:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:30)
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:26)
	at net.minecraft.client.multiplayer.WorldClient.func_184134_a(WorldClient.java:544)
	at net.minecraft.client.multiplayer.WorldClient.func_184148_a(WorldClient.java:532)
	at net.minecraft.world.World.func_184133_a(World.java:1045)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:57)
	at com.lothrazar.cyclicmagic.item.itemblock.ItemBlockScaffolding.func_180614_a(ItemBlockScaffolding.java:81)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:463)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:30)
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:26)
	at net.minecraft.client.multiplayer.WorldClient.func_184134_a(WorldClient.java:544)
	at net.minecraft.client.multiplayer.WorldClient.func_184148_a(WorldClient.java:532)
	at net.minecraft.world.World.func_184133_a(World.java:1045)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:57)
	at com.lothrazar.cyclicmagic.item.itemblock.ItemBlockScaffolding.func_180614_a(ItemBlockScaffolding.java:81)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:463)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lothrazar'/306, l='MpServer', x=-177.07, y=67.50, z=264.66]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-188,64,256), Chunk: (at 4,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 171155 game time, 254870 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityCow['Cow'/128, l='MpServer', x=-170.45, y=64.00, z=250.45], EntityCow['Cow'/129, l='MpServer', x=-170.42, y=64.00, z=251.59], EntityZombie['Zombie'/10753, l='MpServer', x=-137.50, y=44.00, z=207.50], EntityLittleTurtle['Little Turtle'/130, l='MpServer', x=-163.60, y=71.00, z=298.95], EntitySkeleton['Skeleton'/10754, l='MpServer', x=-135.30, y=71.00, z=284.70], EntityMinecartChest['Minecart with Chest'/131, l='MpServer', x=-170.50, y=14.06, z=314.50], EntityZombie['Zombie'/10755, l='MpServer', x=-163.50, y=64.00, z=284.50], EntityCow['Cow'/139, l='MpServer', x=-151.16, y=69.00, z=271.45], EntitySpider['Spider'/10763, l='MpServer', x=-218.50, y=64.00, z=259.50], EntityMinecartChest['Minecart with Chest'/140, l='MpServer', x=-157.50, y=14.06, z=294.50], EntityMinecartChest['Minecart with Chest'/141, l='MpServer', x=-155.50, y=14.06, z=313.50], EntityBat['Bat'/7317, l='MpServer', x=-188.24, y=50.10, z=272.88], EntityZombie['Zombie'/10261, l='MpServer', x=-248.50, y=42.00, z=335.50], EntityCow['Cow'/151, l='MpServer', x=-128.55, y=66.00, z=270.73], EntityBat['Bat'/10651, l='MpServer', x=-170.68, y=49.87, z=284.54], EntityChameleon['Chameleon'/159, l='MpServer', x=-119.50, y=65.00, z=256.50], EntityCow['Cow'/160, l='MpServer', x=-127.53, y=65.00, z=260.58], EntityCow['Cow'/161, l='MpServer', x=-125.79, y=68.00, z=277.51], EntityCow['Cow'/162, l='MpServer', x=-131.18, y=67.00, z=273.50], EntitySpider['Spider'/10667, l='MpServer', x=-159.53, y=68.00, z=254.07], EntityLittleTurtle['Little Turtle'/174, l='MpServer', x=-102.58, y=64.00, z=230.49], EntityBat['Bat'/10802, l='MpServer', x=-223.33, y=27.86, z=219.51], EntityBat['Bat'/10806, l='MpServer', x=-209.25, y=39.02, z=299.25], EntityZombie['Zombie'/10700, l='MpServer', x=-239.50, y=22.00, z=324.50], EntityPlayerSP['Lothrazar'/306, l='MpServer', x=-177.07, y=67.50, z=264.66], EntityItem['item.tile.woodSlab.big_oak'/8784, l='MpServer', x=-182.29, y=64.00, z=249.63], EntitySkeleton['Skeleton'/10704, l='MpServer', x=-217.50, y=28.00, z=222.50], EntitySkeleton['Skeleton'/7255, l='MpServer', x=-186.32, y=52.00, z=280.53], EntitySkeleton['Skeleton'/10585, l='MpServer', x=-100.50, y=71.00, z=256.50], EntityCreeper['Creeper'/10714, l='MpServer', x=-202.50, y=21.00, z=323.50], EntityLittleTurtle['Little Turtle'/91, l='MpServer', x=-234.58, y=64.00, z=206.64], EntityItem['item.tile.dirt.default'/9951, l='MpServer', x=-176.42, y=65.00, z=267.13], EntityZombie['Zombie'/10340, l='MpServer', x=-221.65, y=17.00, z=293.35], EntityCreeper['Creeper'/10599, l='MpServer', x=-239.50, y=45.00, z=307.50], EntityWitch['Witch'/10600, l='MpServer', x=-222.50, y=64.00, z=279.50], EntityZombie['Zombie'/10604, l='MpServer', x=-216.19, y=64.00, z=245.48], EntitySkeleton['Skeleton'/10735, l='MpServer', x=-208.50, y=23.00, z=307.50], EntityItem['item.tile.dirt.default'/9970, l='MpServer', x=-175.37, y=65.00, z=267.88], EntityItem['item.tile.dirt.default'/9972, l='MpServer', x=-174.92, y=67.00, z=268.92], EntityItem['item.tile.dirt.default'/9974, l='MpServer', x=-175.87, y=65.00, z=268.88], EntityItem['item.tile.log.oak'/10616, l='MpServer', x=-179.16, y=64.50, z=267.87], EntityCow['Cow'/126, l='MpServer', x=-171.44, y=64.00, z=251.36], EntityCow['Cow'/127, l='MpServer', x=-171.55, y=64.00, z=250.45]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 213411784 bytes (203 MB) / 853823488 bytes (814 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.0.2010 Optifine OptiFine_1.10.2_HD_U_C2 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJAAAA	Forge{12.18.0.2010} [Minecraft Forge] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.0.7.0.jar) 
	UCHIJAAAA	Ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.0-5.jar) 
	UCHIJAAAA	lazAnvils{1.2.1.3} [Anvil Enchantments] (anvils-1.10.2-1.2.1.3.jar) 
	UCHIJAAAA	JEI{3.7.5.227} [Just Enough Items] (jei_1.10.2-3.7.5.227.jar) 
	UCHIJAAAA	AppleCore{1.3.5} [AppleCore] (AppleCore-mc1.10.2-1.3.5.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.7.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.0.7.0.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	bettercombatmod{1.3.0} [Better Combat] (BetterCombat-1.3.jar) 
	UCHIJAAAA	BetterFoliage{2.0.13} [Better Foliage] (BetterFoliage-MC1.10-2.0.13.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.10-2.1.5.jar) 
	UCHIJAAAA	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCHIJAAAA	combathelp{1.0.3} [Combat Help] (combathelp-1.9.4-1.0.3.jar) 
	UCHIJAAAA	cyclicmagic{1.4.0} [Cyclic] (Cyclic-1.10.2-1.4.0.jar) 
	UCHIJAAAA	Ding{MC1.9.0v2} [Ding] (Ding-1.10.2-1.0.0.jar) 
	UCHIJAAAA	dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial] (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.10-1.2.1.jar) 
	UCHIJAAAA	forgecreeperheal{1.3.0} [Forge Creeper Heal] (forgecreeperheal-1.10.2-1.3.0.jar) 
	UCHIJAAAA	GlobalGameRules{1.0} [Global GameRules] (GlobalGameRules-1.10.2-1.0.jar) 
	UCHIJAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (GrappleHooks-1.10-1.0.8.jar) 
	UCHIJAAAA	gravestone{1.5.1} [Gravestone] (GraveStone Mod 1.5.1.jar) 
	UCHIJAAAA	HoloInventory{2.0.1.135} [HoloInventory] (HoloInventory-1.9.4-2.0.1.135.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.6.41} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.6.41.jar) 
	UCHIJAAAA	kleeslabs{3.3.1} [KleeSlabs] (KleeSlabs-mc1.10-3.3.1.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHIJAAAA	LaserLevel{2.1.0.13} [Laser Level] (LaserLevel-1.10.2-2.1.0.13-universal.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (LemonsTeleporters-1.1.3.jar) 
	UCHIJAAAA	ModLister{1.10-2.1.6} [ModLister] (ModLister-1.10-2.1.6.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAA	notenoughwands{1.3.5} [Not Enough Wands] (notenoughwands-1.9.4-1.3.5.jar) 
	UCHIJAAAA	Quark{beta-44} [Quark] (Quark-beta-44.jar) 
	UCHIJAAAA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-55.jar) 
	UCHIJAAAA	Schematica{1.7.8.150} [Schematica] (Schematica-1.10.2-1.7.8.150-universal.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.10.jar) 
	UCHIJAAAA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (StorageDrawers-1.10-3.1.11.jar) 
	UCHIJAAAA	supercraftingframe{1.2.0.85} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.0.85.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	vc{v0.2.9b-mc1.10.2} [ViesCraft] (ViesCraft-0.2.9b-mc1.10.2.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-beta-44.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.0.7.0.jar)
  
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.0.2010
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Bdubs.zip, HalcyonSky.zip, SimplisticSymmetry1.0.zip, SamsMinecraftBeta.zip, TsutarjaWatermelon.zip
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3540 @ 2.16GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by PrinceOfAmber** [comment]
Fixed in release https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.4.1
