### ISSUE TITLE
1.4.4 Crashes when loading on server

### ISSUE THREAD

**Issue by stevedbarlow** [PrinceOfAmber/Cyclic#61]
`Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$InitGuiEv
ent$Post
        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:790)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:94)
        at com.lothrazar.cyclicmagic.registry.EventRegistry.registerAll(EventRegistry.java:12)
        at com.lothrazar.cyclicmagic.ModMain.onInit(ModMain.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:788)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 37 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
`

**Comment by PrinceOfAmber** [comment]
Thanks for the report, looks like a Gui screen gone wrong.  Sorry, i havent tested on server since 1.4.0.  Ill have a fix out today

**Comment by PrinceOfAmber** [comment]
1.4.5 released to fix this, let me know how it looks on your end

https://minecraft.curseforge.com/projects/cyclic/files/2320355
