### ISSUE TITLE
Sprinkler can sometimes crash when trying to grow an air block - multi block crops (simple corn)

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#620]
Minecraft version & Mod Version: Cyclic-1.12.2-1.10.4.jar

Single player:

Describe problem (what you were doing / what happened):
I was breaking blocks in range of many sprinkler

Crash log (if any):
```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204)
	at panda.corn.objects.BlockCorn.updateTick(BlockCorn.java:119)
	at com.lothrazar.cyclicmagic.component.sprinkler.TileSprinkler.update(TileSprinkler.java:55)
	at net.minecraft.world.World.updateEntities(World.java:1988)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1954)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1171)
	at net.minecraft.client.Minecraft.run(Minecraft.java:436)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
```

**Comment by PrinceOfAmber** [comment]
Seems like partly other mods fault due to 

panda.corn.objects.BlockCorn.updateTick(BlockCorn.java:119)

 but also because the block must have been set in unnatural state due to breaking and force-growing in same instant

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2508575
