### ISSUE TITLE
Latest Ver incompatibility?

### ISSUE THREAD

**Issue by SciMuse** [PrinceOfAmber/Cyclic#836]
Minecraft version & Mod Version: 1.12.2 1.15.9

Single player or Server:sp

Describe problem (what you were doing / what happened): if quark or tropicraft are loaded with 1.15.9 the game crashes while starting it up. last update did something to buckets or item stacks? i tested by making an instance with only these three mods. if cyclic is enabled it doesn't work. they were working. reverting cyclic to previous version, everything runs fine.

Crash log (if any): i have two.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-123.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/10/18 11:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at net.tropicraft.core.common.item.scuba.api.IScubaTank.serializeNBT(IScubaTank.java:21)
	at net.tropicraft.core.common.item.scuba.ItemScubaTank$1.setAirType(ItemScubaTank.java:57)
	at net.tropicraft.core.common.item.scuba.api.IScubaTank.deserializeNBT(IScubaTank.java:28)
	at net.tropicraft.core.common.item.scuba.ItemScubaTank.lambda$initCapabilities$0(ItemScubaTank.java:61)
	at net.tropicraft.core.common.item.scuba.ItemScubaTank$$Lambda$271/1575733998.get(Unknown Source)
	at net.tropicraft.core.common.item.scuba.ScubaCapabilities$3.getCapability(ScubaCapabilities.java:86)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at net.tropicraft.core.common.item.scuba.ItemScubaTank.func_77624_a(ItemScubaTank.java:77)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$null$3(Minecraft.java:593)
	at net.minecraft.client.Minecraft$$Lambda$286/1730200664.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$5(Minecraft.java:596)
	at net.minecraft.client.Minecraft$$Lambda$280/1546855927.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194040_a(SourceFile:35)
	at net.minecraft.client.util.SearchTreeManager.func_110549_a(SourceFile:23)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1080)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1213908136 bytes (1157 MB) / 1783103488 bytes (1700 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID          | Version      | Source                           | Signature                                |
	|:------- |:----------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft   | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJA  | mcp         | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJA  | FML         | 8.0.99.99    | forge-1.12.2-14.23.4.2707.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge       | 14.23.4.2707 | forge-1.12.2-14.23.4.2707.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | quark       | r1.4-123     | Quark-r1.4-123.jar               | None                                     |
	| UCHIJA  | autoreglib  | 1.3-17       | AutoRegLib-1.3-17.jar            | None                                     |
	| UCHIJA  | cyclicmagic | 1.15.9       | Cyclic-1.12.2-1.15.9.jar         | None                                     |
	| UCHIJA  | tropicraft  | 7.1.4.78     | tropicraft-MC1.12.2-7.1.4.78.jar | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.77' Renderer: 'Quadro K4100M/PCIe/SSE2'

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-123.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/10/18 11:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at vazkii.quark.misc.item.ItemSlimeBucket.func_77653_i(ItemSlimeBucket.java:104)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$269/1520575684.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194040_a(SourceFile:35)
	at net.minecraft.client.util.SearchTreeManager.func_110549_a(SourceFile:23)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1080)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 510637560 bytes (486 MB) / 2412249088 bytes (2300 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID          | Version      | Source                           | Signature                                |
	|:------- |:----------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft   | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJA  | mcp         | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJA  | FML         | 8.0.99.99    | forge-1.12.2-14.23.4.2707.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge       | 14.23.4.2707 | forge-1.12.2-14.23.4.2707.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | quark       | r1.4-123     | Quark-r1.4-123.jar               | None                                     |
	| UCHIJA  | autoreglib  | 1.3-17       | AutoRegLib-1.3-17.jar            | None                                     |
	| UCHIJA  | cyclicmagic | 1.15.9       | Cyclic-1.12.2-1.15.9.jar         | None                                     |
	| UCHIJA  | tropicraft  | 7.1.4.78     | tropicraft-MC1.12.2-7.1.4.78.jar | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.77' Renderer: 'Quadro K4100M/PCIe/SSE2'

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Thanks for report, i found a fix for https://github.com/PrinceOfAmber/Cyclic/issues/839 so i will see if that applies here

**Comment by PrinceOfAmber** [comment]
Try this fix https://minecraft.curseforge.com/projects/cyclic/files/2572232

**Comment by SciMuse** [comment]
feed back. it is fixed in the latest version, thank you very much!
