### ISSUE TITLE
Startup Crash with 1.12.2 1.15.10

### ISSUE THREAD

**Issue by CrossJaw** [PrinceOfAmber/Cyclic#844]
Minecraft version & Mod Version: 1.12.2 1.15.10

Single player or Server: Single player (Crashes tend to happen on startup though)

Describe problem (what you were doing / what happened): I was having the item stacking bug of the previous version and then heard this version was released. I downloaded it to my mods file and loaded up the game and got to the title screen before it abruptly crashed with no crash report to be found. I tried again and managed to get into my singleplayer world before it crashed soon after. 

Crash log (if any): https://hastebin.com/qejobuxizo.sql

**Comment by CrossJaw** [comment]
My List of Mods (Not including Cyclic):
AppleSkin-mc1.12-1.0.9.jar
BetterFps-1.4.8.jar
ChestTransporter-1.12.2-2.8.8.jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
CodeChickenLib-1.12.2-3.1.9.344-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
conarm-1.12.2-0.0.20-b.jar (Construct's Armory)
ctwatercan-1.12.2-0.5.6.jar
ElevatorMod-1.12.2-1.3.6.jar
EnderCore-1.12.2-0.5.31.jar
EnderIO-1.12.2-5.0.26.jar
EnderStorage-1.12.2-2.4.3.131-universal.jar
extrautils2-1.12-1.7.6.jar
FoamFix-1.12.2-0.9.4-Anarchy.jar
Hwyla-1.8.26-B41_1.12.2.jar
 InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.40.824.jar
jei_1.12.2-4.9.2.196.jar
Mantle-1.12-1.3.2.24.jar
Mekanism-1.12.2-9.4.11.346.jar
MekanismGenerators-1.12.2-9.4.11.346.jar
metamorph-1.1.5-1.12.2.jar
Netherending-Ores-1.12.2-1.2.jar
OptiFine_1.12.2_HD_U_D1.jar
OreExcavation-1.4.118.jar
Pam's+HarvestCraft+1.12.2a.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
refinedstorage-1.5.34.jar
TConstruct-1.12.2-2.10.1.84.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
TinkerToolLeveling-1.12-1.0.4.jar
 Xaeros_Minimap_1.14.9.1_Forge_1.12.jar
(I copied them from the command prompt, so excuse the file types.)

**Comment by CrossJaw** [comment]
It still crashes without optifine btw.

**Comment by PrinceOfAmber** [comment]
Does it go away when cyclic is removed?


Looking at the crash log cyclic is not mentioned anywhere, something about sky color?

`java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1481)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:463)
	at net.minecraft.world.World.func_72833_a(World.java:1472)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1721)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1273)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by CrossJaw** [comment]
It works just fine without cyclic and with previous versions of cyclic.

All I know is that it just starts to crash when I get into my world or title screen whenever I load up 1.15.10 
I'll try to look into it to see if something else is causing the problem.

**Comment by PrinceOfAmber** [comment]
Thanks, ill see what chagned on my end, 

I updated files on curse to reflect that 1.15.8 is still the Green released most stable version, so it must be something in later versions  https://minecraft.curseforge.com/projects/cyclic/files

**Comment by PrinceOfAmber** [comment]
World loads up just fine in my mod list. shown https://modlister.com/user/Lothrazar 

Since the crash log does not mention cyclic it must be some obscure combination of 2 or more mods from your list, but which ones i have no idea.

**Comment by CrossJaw** [comment]
1.15.11 seems to have fixed my crash

Although I've ran into another bug, but i'll just post as a separate issue.
