### ISSUE TITLE
Block placer causes NullPointerException for blocks using the placer entity

### ISSUE THREAD

**Issue by Zekrom64** [PrinceOfAmber/Cyclic#865]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.15.12

Single player or Server:
Server

Describe problem (what you were doing / what happened):
A player on the server decided to put a market from Farming for Blockheads into a block placer, which relies on the placer entity to determine its direction. Because the block placer passes null, it causes a NullPointerException which crashes the server. When the server crashes, the block placer doesn't remove the item from its inventory, so the server gets stuck crashing on startup.

Crash log (if any):
[crash-2018-06-27_10.19.25-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/2143526/crash-2018-06-27_10.19.25-server.txt)

```
Time: 6/27/18 10:19 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.blay09.mods.farmingforblockheads.block.BlockMarket.func_180642_a(BlockMarket.java:83)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2238)
	at com.lothrazar.cyclicmagic.core.util.UtilPlaceBlocks.placeItemblock(UtilPlaceBlocks.java:95)
	at com.lothrazar.cyclicmagic.block.placer.TileEntityPlacer.func_73660_a(TileEntityPlacer.java:144)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by PrinceOfAmber** [comment]
As far as I can tell, there is no requirement in forge or in vanilla minecraft for this to be non null.  For example, if a command block places blocks there is no player to pass.

The farmingforblockheads authors can correct me if im wrong, but this is something they have to do on their end.

Hopefully they can fix it with a simple

if(player != null) {

...
}

So please report the issue here https://github.com/blay09/FarmingForBlockheads/issues  . You can link this issue as well

If you have questions or if Blay09 wants to contact me i am around on twitter and discord

**Comment by blay09** [comment]
Placer in this instance is not allowed to be null, and should be a fake player in cases of automatic placement. The same issue occurs for example when trying to place Vanilla anvils:

```
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.block.BlockAnvil.getStateForPlacement(BlockAnvil.java:84)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2490)
	at com.lothrazar.cyclicmagic.core.util.UtilPlaceBlocks.placeItemblock(UtilPlaceBlocks.java:95)
	at com.lothrazar.cyclicmagic.block.placer.TileEntityPlacer.update(TileEntityPlacer.java:143)
```

Command blocks don't try to simulate a player placing the block, so they just place it without calling the appropriate functions (which is why it works fine for those).

**Comment by PrinceOfAmber** [comment]
@blay09  Hey i didnt see this reply right away, sorry.  

Ill look into adding a fake player, but you should also do if(player != null) check anyway, since all the code & comments & documentation on this method dont indicate non-null requirements. 


Is there an alternative to "block . getStateForPlacement " that does not take in the player

**Comment by PrinceOfAmber** [comment]
Yep, youre right. exact same error with Anvil

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2601662
