### ISSUE TITLE
Sack of holding dupes ExtraCells devices

### ISSUE THREAD

**Issue by Sleeeper** [PrinceOfAmber/Cyclic#877]
MC 1.12.2
Cyclic-1.12.2-1.15.15.jar
ExtraCells-1.12.2-2.5.13a60.jar

Spotted on server while playing.

Sack of holding keeps data (should return empty) when block is placed back in the world.
So it can be placed again and again infinitely.

**Comment by Sleeeper** [comment]
https://github.com/ExtraCells/ExtraCells2/issues/577

**Comment by PrinceOfAmber** [comment]
Are there any errors in the log when this happens? Possibly related https://github.com/PrinceOfAmber/Cyclic/issues/876

**Comment by PrinceOfAmber** [comment]
I got it to replicate actually

[21:40:36] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
	at appeng.me.GridNode.loadFromNBT(GridNode.java:343) ~[GridNode.class:?]
	at extracells.tileentity.TileEntityFluidFiller.func_145839_a(TileEntityFluidFiller.java:302) ~[TileEntityFluidFiller.class:?]
	at com.lothrazar.cyclicmagic.item.tiletransporter.ItemChestSack.placeStoredTileEntity(ItemChestSack.java:109) ~[ItemChestSack.class:?]
	at com.lothrazar.cyclicmagic.item.tiletransporter.ItemChestSack.func_180614_a(ItemChestSack.java:74) ~[ItemChestSack.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:875) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by PrinceOfAmber** [comment]
Looks like there is an error coming back from at extracells.tileentity.TileEntityFluidFiller, 


so the best I can do on my end is not dupe the block which means it might get stuck in the item sack. to prevent errors and loss.  

If it doesnt already have a blacklist, i can add a blacklist to this item too

**Comment by Sleeeper** [comment]
It only dupes those 3 things:
extracells:fluidcrafter
extracells:ecbaseblock
extracells:fluidfiller
On the server I play they were just added to sack's blacklist for now.

**Comment by PrinceOfAmber** [comment]
Found a fix, also adding these to default blacklist

       "extracells:fluidcrafter",
        "extracells:ecbaseblock",
        "extracells:fluidfiller",
        "refinedstorage:disk_drive"

**Comment by PrinceOfAmber** [comment]
Release is out with these changes https://minecraft.curseforge.com/projects/cyclic/files/2588760
