### ISSUE TITLE
Crash when using Monster Ball in dispenser

### ISSUE THREAD

**Issue by Partonetrain** [PrinceOfAmber/Cyclic#905]
Minecraft version & Mod Version:
1.12.2 Forge-14.23.4.2756
Cyclic 1.12.2-1.16.10

Single player or Server:
Singleplayer, but it appears to be a server crash - crash report was named crash-2018-08-19_15.35.49-server.txt

Describe problem (what you were doing / what happened):

Put a Monster Ball (cyclic:magic_net) in a dispenser. Fire the dispenser. Game crashes.
Doesn't seem to matter if it's aimed at a mob or not.

Crash log (if any):

```
--- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (elulib-0.1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (Quark-r1.5-127.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 8/19/18 3:35 PM
Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
	at net.minecraft.entity.projectile.EntityThrowable.<init>(EntityThrowable.java:58)
	at com.lothrazar.cyclicmagic.core.entity.EntityThrowableDispensable.<init>(EntityThrowableDispensable.java:39)
	at com.lothrazar.cyclicmagic.item.mobcapture.EntityMagicNetEmpty.<init>(EntityMagicNetEmpty.java:66)
	at com.lothrazar.cyclicmagic.item.mobcapture.ItemProjectileMagicNet.getThrownEntity(ItemProjectileMagicNet.java:66)
	at com.lothrazar.cyclicmagic.tweak.dispenser.BehaviorProjectileThrowable.func_82499_a(BehaviorProjectileThrowable.java:44)
	at net.minecraft.dispenser.BehaviorProjectileDispense.func_82487_b(SourceFile:21)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12)
	at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:119)
	at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:143)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.projectile.EntityThrowable.<init>(EntityThrowable.java:58)
	at com.lothrazar.cyclicmagic.core.entity.EntityThrowableDispensable.<init>(EntityThrowableDispensable.java:39)
	at com.lothrazar.cyclicmagic.item.mobcapture.EntityMagicNetEmpty.<init>(EntityMagicNetEmpty.java:66)
	at com.lothrazar.cyclicmagic.item.mobcapture.ItemProjectileMagicNet.getThrownEntity(ItemProjectileMagicNet.java:66)
	at com.lothrazar.cyclicmagic.tweak.dispenser.BehaviorProjectileThrowable.func_82499_a(BehaviorProjectileThrowable.java:44)
	at net.minecraft.dispenser.BehaviorProjectileDispense.func_82487_b(SourceFile:21)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12)
	at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:119)
	at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:143)

-- Block being ticked --
Details:
	Block: minecraft:dispenser[facing=north,triggered=true]
	Block location: World: (-603,64,-12), Chunk: (at 5,4,4 in -38,-1; contains blocks -608,0,-16 to -593,255,-1), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: New World11
	All players: 1 total; [EntityPlayerMP['Partonetrain'/1026, l='New World11', x=-600.08, y=64.00, z=-12.85]]
	Chunk stats: ServerChunkCache: 1361 Drop: 0
	Level seed: 5085520211955749679
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (28,64,216), Chunk: (at 12,4,8 in 1,13; contains blocks 16,0,208 to 31,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13728 game time, 13728 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 102717 (now: false), thunder time: 48342 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1589562728 bytes (1515 MB) / 6226444288 bytes (5938 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.4.2756 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                          | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2756.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2756             | forge-1.12.2-14.23.4.2756.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | elucore                           | 1.0                      | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | playerschoice                     | 1.2-4                    | PlayersChoice 1.2-4.jar                         | None                                     |
	| UCHIJAAAA | akashictome                       | 1.2-10                   | AkashicTome-1.2-10.jar                          | None                                     |
	| UCHIJAAAA | craftstudioapi                    | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJAAAA | quark                             | r1.5-127                 | Quark-r1.5-127.jar                              | None                                     |
	| UCHIJAAAA | animania                          | 1.5.1.1                  | animania-1.12.2-1.5.1.1.jar                     | None                                     |
	| UCHIJAAAA | crafttweaker                      | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | mtlib                             | 3.0.5                    | MTLib-3.0.5.jar                                 | None                                     |
	| UCHIJAAAA | modtweaker                        | 4.0.13                   | modtweaker-4.0.13.jar                           | None                                     |
	| UCHIJAAAA | jei                               | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHIJAAAA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJAAAA | autoreglib                        | 1.3-20                   | AutoRegLib-1.3-20.jar                           | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | betterfoliage                     | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCHIJAAAA | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAA | blockcraftery                     | 0.1.3                    | blockcraftery-0.1.3.jar                         | None                                     |
	| UCHIJAAAA | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCHIJAAAA | chiselsandbits                    | 14.21                    | chiselsandbits-14.21.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                          | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cyclopscore                       | 0.11.8                   | CyclopsCore-1.12.2-0.11.8.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | colossalchests                    | 1.6.11                   | ColossalChests-1.12.2-1.6.11.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.37            | EnderCore-1.12.2-0.5.37.jar                     | None                                     |
	| UCHIJAAAA | thermalfoundation                 | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion                  | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | enderio                           | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | twilightforest                    | 3.8.654                  | twilightforest-1.12.2-3.8.654-universal.jar     | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | conarm                            | 1.0.2                    | conarm-1.12.2-1.0.2.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | controlling                       | 3.0.6                    | Controlling-3.0.6.jar                           | None                                     |
	| UCHIJAAAA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | creeperconfetti                   | 1.4.2                    | creeperconfetti-1.4.2.jar                       | None                                     |
	| UCHIJAAAA | crissaegrim                       | 0.1.1                    | crissaegrim-0.1.1.jar                           | None                                     |
	| UCHIJAAAA | cyclicmagic                       | 1.16.10                  | Cyclic-1.12.2-1.16.10.jar                       | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| UCHIJAAAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJAAAA | p455w0rdslib                      | 2.0.32                   | p455w0rdslib-1.12-2.0.32.jar                    | None                                     |
	| UCHIJAAAA | danknull                          | 1.4.33                   | DankNull-1.12-1.4.33.jar                        | None                                     |
	| UCHIJAAAA | discordsuite                      | 2.2.4                    | DiscordSuite-2.2.4.jar                          | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | ftblib                            | 5.2.0.38                 | FTBLib-5.2.0.38.jar                             | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UCHIJAAAA | f0-resources                      | 1.0.3                    | Factory0-Resources-1.12.2-1.0.3.jar             | None                                     |
	| UCHIJAAAA | ftbguides                         | 1.0.2.17                 | FTBGuides-1.0.2.17.jar                          | None                                     |
	| UCHIJAAAA | ftbg                              | 1.12.1-1.0.07            | ftbg-1.12.1-1.0.7.jar                           | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | ftbutilities                      | 5.2.0.39                 | FTBUtilities-5.2.0.39.jar                       | None                                     |
	| UCHIJAAAA | geolosys                          | 2.1.1                    | Geolosys-1.12.2-2.1.1.jar                       | None                                     |
	| UCHIJAAAA | initialinventory                  | 2.0.2                    | InitialInventory-3.0.0.jar                      | None                                     |
	| UCHIJAAAA | inventorysorter                   | 1.13.3+57                | inventorysorter-1.12.2-1.13.3+57.jar            | None                                     |
	| UCHIJAAAA | itemscroller                      | 0.12.0                   | itemscroller-1.12.2-0.12.0.jar                  | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | oreexcavation                     | 1.4.119                  | OreExcavation-1.4.119.jar                       | None                                     |
	| UCHIJAAAA | placebo                           | 1.4.1                    | Placebo-1.12.2-1.4.1.jar                        | None                                     |
	| UCHIJAAAA | plustic                           | 6.5.2.0                  | plustic-6.5.2.0.jar                             | None                                     |
	| UCHIJAAAA | quarkoddities                     | 1                        | QuarkOddities-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJAAAA | storagenetwork                    | 1.12.2-1.2.9             | SimpleStorageNetwork-1.12.2-1.2.9.jar           | None                                     |
	| UCHIJAAAA | thermaldynamics                   | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalinnovation                 | 0.3.0                    | ThermalInnovation-1.12.2-0.3.0.7-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
	| UCHIJAAAA | toastcontrol                      | 1.7.0                    | Toast Control-1.12.2-1.7.0.jar                  | None                                     |
	| UCHIJAAAA | tombmanygraves2api                | 1.12.2-1.0.0             | tombmanygraves2api-1.12.2-1.0.0.jar             | None                                     |
	| UCHIJAAAA | tombmanygraves                    | 1.12-4.1.0               | TombManyGraves-1.12-4.1.0.jar                   | None                                     |
	| UCHIJAAAA | torchmaster                       | 1.6.4.62                 | torchmaster_1.12.2-1.6.4.62.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAAAA | totemic                           | 1.12.2-0.11.3            | Totemic-1.12.2-0.11.3.jar                       | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UCHIJAAAA | traverse                          | 1.5.5                    | Traverse-1.12.2-1.5.5-65.jar                    | None                                     |
	| UCHIJAAAA | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHIJAAAA | wawla                             | 2.5.257                  | Wawla-1.12.2-2.5.257.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | waystones                         | 4.0.54                   | Waystones_1.12.2-4.0.54.jar                     | None                                     |
	| UCHIJAAAA | reauth                            | 3.6.0                    | reauth-3.6.0.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJAAAA | elulib                            | 0.1.12                   | elulib-0.1.12.jar                               | None                                     |

	Loaded coremods (and transformers): 
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.5-127.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Partonetrain'/1026, l='New World11', x=-600.08, y=64.00, z=-12.85]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

edit: formatting

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2609136
