### ISSUE TITLE
Dupe potion registry?

### ISSUE THREAD

**Issue by darkhax** [PrinceOfAmber/Cyclic#945]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.17.2

Single player or Server: SP

Describe problem (what you were doing / what happened):

```
[18:51:05] [main/WARN] [FML]: * Registry PotionType: The object com.lothrazar.cyclicmagic.potion.PotionTypeCyclic@3609db54 has been registered twice for the same name cyclicmagic:saturation.
[18:51:05] [main/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:301)
[18:51:05] [main/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:282)
[18:51:05] [main/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:115)
[18:51:05] [main/WARN] [FML]: *  at com.lothrazar.cyclicmagic.potion.PotionTypeRegistry.onRegistryEvent(PotionTypeRegistry.java:55)
[18:51:05] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_810_PotionTypeRegistry_onRegistryEvent_Register.invoke(.dynamic)
[18:51:05] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)...
[18:51:05] [main/WARN] [FML]: ****************************************
```

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yeah i did see this once i finally upgraded to the newer versions of forge, never was printed before.

I must be adding the level 2 potion type wrong

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
