### ISSUE TITLE
1.7.6 exchange scepters cause exceptions if you use them too fast

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#99]
log
http://pastebin.com/9vRpZydc

Related to falling gravel or item entities

**Comment by PrinceOfAmber** [comment]
I fixed some things on my end, but it may be a side effect with the real line : 


dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.

**Comment by PrinceOfAmber** [comment]
Nope still happens even when Dyn surroundings is gone

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 25/09/16 9:03 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:280)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 108814600 bytes (103 MB) / 687816704 bytes (655 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2093 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJAAAA	Forge{12.18.1.2093} [Minecraft Forge] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJAAAA	cyclicmagic{1.7.7} [Cyclic] (Cyclic-1.10.2-1.7.7DEV.jar) 
	UCHIJAAAA	JEI{3.10.0.263} [Just Enough Items] (jei_1.10.2-3.10.0.263.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LazarussLong'/496, l='BLARG', x=151.49, y=62.00, z=12.62]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by PrinceOfAmber** [comment]
De-obfuscated error from debug code so it has real line numbers


2016-09-25 21:08:59,614 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-09-25 21:08:59,615 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:08:59] [main/INFO] [GradleStart]: Extra: []
[21:08:59] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Sam/.gradle/caches/minecraft/assets, --assetIndex, 1.10, --accessToken{REDACTED}, --version, 1.10.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[21:08:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:08:59] [main/INFO] [FML]: Forge Mod Loader version 12.18.1.2044 for Minecraft 1.10.2 loading
[21:08:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_101
[21:08:59] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:08:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:08:59] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[21:08:59] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[21:08:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:08:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:08:59] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:09:00] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[21:09:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:09:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:09:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:09:00] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:09:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:09:00] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2016-09-25 21:09:01,260 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-09-25 21:09:01,276 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-09-25 21:09:01,278 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:09:01] [Client thread/INFO]: Setting user: Player988
[21:09:04] [Client thread/WARN]: Skipping bad option: lastServer:
[21:09:04] [Client thread/INFO]: LWJGL Version: 2.9.4
[21:09:04] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:221]: ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 25/09/16 9:09 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 611758168 bytes (583 MB) / 861929472 bytes (822 MB) up to 3803185152 bytes (3627 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.33' Renderer: 'GeForce GT 730/PCIe/SSE2'
[21:09:04] [Client thread/INFO] [FML]: MinecraftForge v12.18.1.2044 Initialized
[21:09:04] [Client thread/INFO] [FML]: Replaced 233 ore recipes
[21:09:04] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[21:09:04] [Client thread/INFO] [FML]: Searching P:\eclipseWorkspace\cyclic\run\mods for mods
[21:09:05] [Client thread/WARN] [cyclicmagic]: Mod cyclicmagic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.7.7
[21:09:05] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[21:09:06] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, cyclicmagic] at CLIENT
[21:09:06] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, cyclicmagic] at SERVER
[21:09:06] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Cyclic
[21:09:06] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[21:09:06] [Client thread/INFO] [FML]: Found 423 ObjectHolder annotations
[21:09:06] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[21:09:06] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[21:09:06] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[21:09:06] [Forge Version Check/INFO] [ForgeVersionCheck]: [cyclicmagic] Starting version check at https://raw.githubusercontent.com/PrinceOfAmber/CyclicMagic/master/update.json
[21:09:07] [Client thread/INFO] [FML]: Applying holder lookups
[21:09:07] [Client thread/INFO] [FML]: Holder lookups applied
[21:09:07] [Client thread/INFO] [FML]: Injecting itemstacks
[21:09:07] [Client thread/INFO] [FML]: Itemstack injection complete
[21:09:07] [Forge Version Check/INFO] [ForgeVersionCheck]: [cyclicmagic] Found status: AHEAD Target: null
[21:09:07] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[21:09:07] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: OUTDATED Target: 12.18.1.2094
[21:09:08] [Sound Library Loader/INFO]: Starting up SoundSystem...
[21:09:08] [Thread-8/INFO]: Initializing LWJGL OpenAL
[21:09:08] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:09:08] [Thread-8/INFO]: OpenAL initialized.
[21:09:09] [Sound Library Loader/INFO]: Sound engine started
[21:09:10] [Client thread/INFO] [FML]: Max texture size: 16384
[21:09:10] [Client thread/INFO]: Created: 16x16 textures-atlas
[21:09:11] [Client thread/INFO] [FML]: Injecting itemstacks
[21:09:11] [Client thread/INFO] [FML]: Itemstack injection complete
[21:09:11] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[21:09:11] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Cyclic
[21:09:13] [Client thread/INFO]: SoundSystem shutting down...
[21:09:13] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[21:09:13] [Sound Library Loader/INFO]: Starting up SoundSystem...
[21:09:13] [Thread-10/INFO]: Initializing LWJGL OpenAL
[21:09:13] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:09:13] [Thread-10/INFO]: OpenAL initialized.
[21:09:14] [Sound Library Loader/INFO]: Sound engine started
[21:09:15] [Client thread/INFO] [FML]: Max texture size: 16384
[21:09:15] [Client thread/INFO]: Created: 1024x512 textures-atlas
[21:09:15] [Client thread/WARN]: Skipping bad option: lastServer:
[21:09:16] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[21:10:20] [Server thread/INFO]: Starting integrated minecraft server version 1.10.2
[21:10:20] [Server thread/INFO]: Generating keypair
[21:10:20] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[21:10:21] [Server thread/INFO] [FML]: Applying holder lookups
[21:10:21] [Server thread/INFO] [FML]: Holder lookups applied
[21:10:21] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@362bf7ed)
[21:10:21] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@362bf7ed)
[21:10:21] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@362bf7ed)
[21:10:21] [Server thread/INFO]: Preparing start region for level 0
[21:10:22] [Server thread/INFO]: Changing view distance to 12, from 10
[21:10:23] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[21:10:23] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[21:10:23] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 4 mods : FML@8.0.99.99,Forge@12.18.1.2044,mcp@9.19,cyclicmagic@1.7.7
[21:10:23] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[21:10:23] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[21:10:23] [Server thread/INFO]: Player988[local:E:cb9facd2] logged in with entity id 171 at (-584.8197526284864, 64.0, 228.91436273164257)
[21:10:23] [Server thread/INFO]: Player988 joined the game
[21:10:24] [Server thread/INFO]: Saving and pausing game...
[21:10:24] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[21:10:24] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[21:10:24] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[21:10:24] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3b009874[id=d1a76729-1ccb-3de3-b2b3-c7efa54f7c6f,name=Player988,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:59) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:56) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:165) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.getProfileProperties(Minecraft.java:3060) [Minecraft.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SkinManager.java:131) [SkinManager$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[21:10:30] [Server thread/INFO]: Player988 has just earned the achievement [Taking Inventory]
[21:10:30] [Client thread/INFO]: [CHAT] Player988 has just earned the achievement [Taking Inventory]
[21:10:36] [Server thread/INFO]: [Player988: Set own game mode to Creative Mode]
[21:10:36] [Client thread/INFO]: [CHAT] Your game mode has been updated to Creative Mode
[21:10:51] [Client thread/INFO]: [CHAT] 3x3
[21:10:52] [Client thread/INFO]: [CHAT] 5x5
[21:10:53] [Client thread/INFO]: [CHAT] 7x7
[21:10:54] [Client thread/INFO]: [CHAT] 9x9
[21:10:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:728) ~[WorldServer.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772) ~[MinecraftServer.class:?]
	... 4 more
[21:10:56] [Server thread/ERROR]: This crash report has been saved to: P:\eclipseWorkspace\cyclic\run\.\crash-reports\crash-2016-09-25_21.10.56-server.txt
[21:10:56] [Server thread/INFO]: Stopping server
[21:10:56] [Server thread/INFO]: Saving players
[21:10:56] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 25/09/16 9:10 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:728)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:728)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Player988'/171, l='New World', x=-583.65, y=63.00, z=243.66]]
	Chunk stats: ServerChunkCache: 891 Drop: 0
	Level seed: 2749373541708300573
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-236,64,237), Chunk: (at 4,4,13 in -15,14; contains blocks -240,0,224 to -225,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 176687 game time, 6250 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 72395 (now: false), thunder time: 54444 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 999575696 bytes (953 MB) / 1877999616 bytes (1791 MB) up to 3803185152 bytes (3627 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2044 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.10.2-12.18.1.2044.jar) 
	UCHIJAAAA	Forge{12.18.1.2044} [Minecraft Forge] (forgeSrc-1.10.2-12.18.1.2044.jar) 
	UCHIJAAAA	cyclicmagic{1.7.7} [Cyclic] (bin) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Player988'/171, l='New World', x=-583.65, y=63.00, z=243.66]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[21:10:56] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: #@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2016-09-25_21.10.56-server.txt
[21:10:56] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[21:10:56] [Server thread/INFO]: Saving worlds
[21:10:56] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[21:10:56] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[21:10:56] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[21:10:57] [Server thread/INFO] [FML]: Unloading dimension 0
[21:10:57] [Server thread/INFO] [FML]: Unloading dimension -1
[21:10:57] [Server thread/INFO] [FML]: Unloading dimension 1
[21:10:57] [Server thread/INFO] [FML]: Applying holder lookups
[21:10:57] [Server thread/INFO] [FML]: Holder lookups applied
[21:10:57] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[21:10:57] [Client thread/INFO] [FML]: Server terminated.
[21:10:57] [Client Shutdown Thread/INFO]: Stopping server
[21:10:57] [Client Shutdown Thread/INFO]: Saving players
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by PrinceOfAmber** [comment]
Fixed in https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.7.7
