### ISSUE TITLE
1.17.8 crash

### ISSUE THREAD

**Issue by boosterdev** [PrinceOfAmber/Cyclic#992]
Minecraft version & Mod Version:
1.17.8

Single player or Server:
Server

Describe problem (what you were doing / what happened):

Crash log (if any):
`[09:55:23] [Server thread/WARN] [FML]: Registry EntityEntry: Override did not have an associated owner object. Name: cyclicmagic:torchbolt Value: net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry@29d39b0c
[09:55:23] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:548) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529) ~[GameData.class:?]
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235) ~[GameData.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by kellixon** [comment]
Confirm, too crash minecraft.

**Comment by josephcsible** [comment]
This isn't exclusive to servers. Clients will also crash on startup with the same error.

**Comment by ericcotelnu** [comment]
Gonna try the fixed version, for testing purposes.

**Comment by ericcotelnu** [comment]
No syntax error, but when loading into Forge it buggers out due to it not being initialised? Am I reading that right? (The bugfix) - I'm not a programmer ;).

**Comment by ericcotelnu** [comment]
It works, started up just fine. TYVM :D.
